<Project Sdk="Microsoft.NET.Sdk.Web">

  <ItemGroup>
    <ProjectReference Include="..\BuildingBlocks\BotGlobal.Contracts\BotGlobal.Contracts.csproj" />
    <ProjectReference Include="..\Modules\Catalog\BotGlobal.Catalog\BotGlobal.Catalog.csproj" />
    <ProjectReference Include="..\Modules\Calling\BotGlobal.Calling\BotGlobal.Calling.csproj" />
    <ProjectReference Include="..\Modules\Identity\BotGlobal.Identity\BotGlobal.Identity.csproj" />
    <ProjectReference Include="..\Modules\Notifications\BotGlobal.Notifications\BotGlobal.Notifications.csproj" />
    <ProjectReference Include="..\Modules\Realtime\BotGlobal.Realtime\BotGlobal.Realtime.csproj" />
    <ProjectReference Include="..\Modules\Communication\BotGlobal.Communication\BotGlobal.Communication.csproj" />
    <ProjectReference Include="..\Modules\PlatformClients\BotGlobal.PlatformClients\BotGlobal.PlatformClients.csproj" />
    <ProjectReference Include="..\Modules\Pairing\BotGlobal.Pairing\BotGlobal.Pairing.csproj" />
    <ProjectReference Include="..\Modules\Games\BotGlobal.Games\BotGlobal.Games.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="10.0.10">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="Swashbuckle.AspNetCore" Version="10.2.3" />
  </ItemGroup>

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UserSecretsId>846df752-33a4-4477-a65f-0da9f2d65e50</UserSecretsId>
  </PropertyGroup>

</Project>
