// <auto-generated />
using System;
using BotGlobal.Notifications.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BotGlobal.Notifications.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(NotificationsDbContext))]
    [Migration("20260821164303_InitialNotificationCampaigns")]
    partial class InitialNotificationCampaigns
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("notifications")
                .HasAnnotation("ProductVersion", "10.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("BotGlobal.Notifications.Domain.NotificationCampaign", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("AudienceAsOfUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<int>("AudienceDeviceCount")
                        .HasColumnType("int");

                    b.Property<Guid?>("AudienceExpansionCursor")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("AudienceKind")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset?>("AudienceLeaseExpiresAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<Guid?>("AudienceLeaseId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("AudienceSubjectCount")
                        .HasColumnType("int");

                    b.Property<string>("BodyAr")
                        .IsRequired()
                        .HasMaxLength(4000)
                        .HasColumnType("nvarchar(4000)");

                    b.Property<string>("BodyEn")
                        .IsRequired()
                        .HasMaxLength(4000)
                        .HasColumnType("nvarchar(4000)");

                    b.Property<DateTimeOffset?>("CompletedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("CreatedByDisplayNameSnapshot")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<Guid>("CreatedByUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("ExpiredCount")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset>("ExpiresAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<int>("FailedCount")
                        .HasColumnType("int");

                    b.Property<int>("FcmAcceptedCount")
                        .HasColumnType("int");

                    b.Property<string>("IdempotencyKey")
                        .IsRequired()
                        .HasMaxLength(200)
                        .IsUnicode(false)
                        .HasColumnType("varchar(200)");

                    b.Property<bool>("IsAudienceExpansionComplete")
                        .HasColumnType("bit");

                    b.Property<int>("PendingCount")
                        .HasColumnType("int");

                    b.Property<string>("PlatformClientDisplayNameSnapshot")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<Guid>("PlatformClientId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("PlatformClientKeySnapshot")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("Priority")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset?>("ProcessingStartedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<int>("PushCapableDeviceCount")
                        .HasColumnType("int");

                    b.Property<string>("RequestFingerprint")
                        .IsRequired()
                        .HasMaxLength(64)
                        .IsUnicode(false)
                        .HasColumnType("varchar(64)");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<int>("SignalRDispatchedCount")
                        .HasColumnType("int");

                    b.Property<int>("SkippedCount")
                        .HasColumnType("int");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<string>("TitleAr")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("TitleEn")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("CreatedByUserId", "IdempotencyKey")
                        .IsUnique()
                        .HasDatabaseName("UX_NotificationCampaigns_Admin_IdempotencyKey");

                    b.HasIndex("PlatformClientId", "CreatedAtUtc")
                        .HasDatabaseName("IX_NotificationCampaigns_PlatformClient_CreatedAtUtc");

                    b.HasIndex("Status", "AudienceLeaseExpiresAtUtc")
                        .HasDatabaseName("IX_NotificationCampaigns_AudienceWork");

                    b.ToTable("NotificationCampaigns", "notifications", t =>
                        {
                            t.HasCheckConstraint("CK_NotificationCampaigns_AudienceKind", "[AudienceKind] = 1");

                            t.HasCheckConstraint("CK_NotificationCampaigns_AudienceLease", "([AudienceLeaseId] IS NULL AND [AudienceLeaseExpiresAtUtc] IS NULL) OR ([AudienceLeaseId] IS NOT NULL AND [AudienceLeaseExpiresAtUtc] IS NOT NULL)");

                            t.HasCheckConstraint("CK_NotificationCampaigns_Counts", "[AudienceSubjectCount] >= 0 AND [AudienceDeviceCount] >= 0 AND [PushCapableDeviceCount] >= 0 AND [PendingCount] >= 0 AND [SignalRDispatchedCount] >= 0 AND [FcmAcceptedCount] >= 0 AND [FailedCount] >= 0 AND [SkippedCount] >= 0 AND [ExpiredCount] >= 0");

                            t.HasCheckConstraint("CK_NotificationCampaigns_Lifetime", "[ExpiresAtUtc] > [CreatedAtUtc]");

                            t.HasCheckConstraint("CK_NotificationCampaigns_Priority", "[Priority] IN (1, 2)");

                            t.HasCheckConstraint("CK_NotificationCampaigns_Status", "[Status] BETWEEN 1 AND 7");
                        });
                });

            modelBuilder.Entity("BotGlobal.Notifications.Domain.NotificationRecipient", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("AttemptCount")
                        .HasColumnType("int");

                    b.Property<Guid>("CampaignId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("DeviceNameSnapshot")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<DateTimeOffset?>("DispatchedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset>("ExpiresAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("InstallationIdSnapshot")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTimeOffset?>("LastAttemptAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("LastSafeErrorCode")
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("LastTransport")
                        .HasMaxLength(32)
                        .IsUnicode(false)
                        .HasColumnType("varchar(32)");

                    b.Property<DateTimeOffset?>("LeaseExpiresAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<Guid?>("LeaseId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("MobileDeviceId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset?>("NextAttemptAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("PlatformSnapshot")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CampaignId", "MobileDeviceId")
                        .IsUnique()
                        .HasDatabaseName("UX_NotificationRecipients_Campaign_Device");

                    b.HasIndex("Status", "NextAttemptAtUtc", "LeaseExpiresAtUtc")
                        .HasDatabaseName("IX_NotificationRecipients_DispatchWork");

                    b.ToTable("NotificationRecipients", "notifications", t =>
                        {
                            t.HasCheckConstraint("CK_NotificationRecipients_AttemptCount", "[AttemptCount] >= 0");

                            t.HasCheckConstraint("CK_NotificationRecipients_Lease", "([LeaseId] IS NULL AND [LeaseExpiresAtUtc] IS NULL) OR ([LeaseId] IS NOT NULL AND [LeaseExpiresAtUtc] IS NOT NULL)");

                            t.HasCheckConstraint("CK_NotificationRecipients_NextAttempt", "([Status] IN (1, 2) AND [NextAttemptAtUtc] IS NOT NULL) OR ([Status] IN (3, 4, 5, 6, 7) AND [NextAttemptAtUtc] IS NULL)");

                            t.HasCheckConstraint("CK_NotificationRecipients_Status", "[Status] BETWEEN 1 AND 7");
                        });
                });

            modelBuilder.Entity("BotGlobal.Notifications.Domain.NotificationRecipient", b =>
                {
                    b.HasOne("BotGlobal.Notifications.Domain.NotificationCampaign", "Campaign")
                        .WithMany()
                        .HasForeignKey("CampaignId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Campaign");
                });
#pragma warning restore 612, 618
        }
    }
}
