// <auto-generated />
using System;
using BotGlobal.Notifications.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BotGlobal.Notifications.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(NotificationsDbContext))]
    partial class NotificationsDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("notifications")
                .HasAnnotation("ProductVersion", "10.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("BotGlobal.Notifications.Domain.NotificationCampaign", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("AudienceAsOfUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<int>("AudienceDeviceCount")
                        .HasColumnType("int");

                    b.Property<Guid?>("AudienceExpansionCursor")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("AudienceKind")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset?>("AudienceLeaseExpiresAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<Guid?>("AudienceLeaseId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("AudienceSubjectCount")
                        .HasColumnType("int");

                    b.Property<string>("BodyAr")
                        .IsRequired()
                        .HasMaxLength(4000)
                        .HasColumnType("nvarchar(4000)");

                    b.Property<string>("BodyEn")
                        .IsRequired()
                        .HasMaxLength(4000)
                        .HasColumnType("nvarchar(4000)");

                    b.Property<DateTimeOffset?>("CompletedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("CreatedByDisplayNameSnapshot")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<Guid>("CreatedByUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("ExpiredCount")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset>("ExpiresAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<int>("FailedCount")
                        .HasColumnType("int");

                    b.Property<int>("FcmAcceptedCount")
                        .HasColumnType("int");

                    b.Property<string>("IdempotencyKey")
                        .IsRequired()
                        .HasMaxLength(200)
                        .IsUnicode(false)
                        .HasColumnType("varchar(200)");

                    b.Property<bool>("IsAudienceExpansionComplete")
                        .HasColumnType("bit");

                    b.Property<int>("PendingCount")
                        .HasColumnType("int");

                    b.Property<string>("PlatformClientDisplayNameSnapshot")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<Guid>("PlatformClientId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("PlatformClientKeySnapshot")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("Priority")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset?>("ProcessingStartedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<int>("PushCapableDeviceCount")
                        .HasColumnType("int");

                    b.Property<string>("RequestFingerprint")
                        .IsRequired()
                        .HasMaxLength(64)
                        .IsUnicode(false)
                        .HasColumnType("varchar(64)");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<int>("SignalRDispatchedCount")
                        .HasColumnType("int");

                    b.Property<int>("SkippedCount")
                        .HasColumnType("int");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<string>("TitleAr")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("TitleEn")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("CreatedByUserId", "IdempotencyKey")
                        .IsUnique()
                        .HasDatabaseName("UX_NotificationCampaigns_Admin_IdempotencyKey");

                    b.HasIndex("PlatformClientId", "CreatedAtUtc")
                        .HasDatabaseName("IX_NotificationCampaigns_PlatformClient_CreatedAtUtc");

                    b.HasIndex("Status", "AudienceLeaseExpiresAtUtc")
                        .HasDatabaseName("IX_NotificationCampaigns_AudienceWork");

                    b.ToTable("NotificationCampaigns", "notifications", t =>
                        {
                            t.HasCheckConstraint("CK_NotificationCampaigns_AudienceKind", "[AudienceKind] = 1");

                            t.HasCheckConstraint("CK_NotificationCampaigns_AudienceLease", "([AudienceLeaseId] IS NULL AND [AudienceLeaseExpiresAtUtc] IS NULL) OR ([AudienceLeaseId] IS NOT NULL AND [AudienceLeaseExpiresAtUtc] IS NOT NULL)");

                            t.HasCheckConstraint("CK_NotificationCampaigns_Counts", "[AudienceSubjectCount] >= 0 AND [AudienceDeviceCount] >= 0 AND [PushCapableDeviceCount] >= 0 AND [PendingCount] >= 0 AND [SignalRDispatchedCount] >= 0 AND [FcmAcceptedCount] >= 0 AND [FailedCount] >= 0 AND [SkippedCount] >= 0 AND [ExpiredCount] >= 0");

                            t.HasCheckConstraint("CK_NotificationCampaigns_Lifetime", "[ExpiresAtUtc] > [CreatedAtUtc]");

                            t.HasCheckConstraint("CK_NotificationCampaigns_Priority", "[Priority] IN (1, 2)");

                            t.HasCheckConstraint("CK_NotificationCampaigns_Status", "[Status] BETWEEN 1 AND 8");
                        });
                });

            modelBuilder.Entity("BotGlobal.Notifications.Domain.NotificationDeliveryAttempt", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ApplicationId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("AttemptNumber")
                        .HasColumnType("int");

                    b.Property<Guid>("CampaignId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset?>("CompletedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("DeliveryKey")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)");

                    b.Property<Guid>("LeaseId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("MobileDeviceId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("NotificationRecipientId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset?>("ProviderInvocationStartedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("ProviderMessageId")
                        .HasMaxLength(500)
                        .IsUnicode(false)
                        .HasColumnType("varchar(500)");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<string>("SafeErrorCode")
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<string>("Transport")
                        .HasMaxLength(32)
                        .IsUnicode(false)
                        .HasColumnType("varchar(32)");

                    b.HasKey("Id");

                    b.HasIndex("NotificationRecipientId", "AttemptNumber")
                        .IsUnique()
                        .HasDatabaseName("UX_NotificationDeliveryAttempts_Recipient_Number");

                    b.HasIndex("Status", "CompletedAtUtc")
                        .HasDatabaseName("IX_NotificationDeliveryAttempts_Recovery");

                    b.HasIndex("ApplicationId", "CampaignId", "DeliveryKey")
                        .HasDatabaseName("IX_NotificationDeliveryAttempts_Application_Campaign_Delivery");

                    b.ToTable("NotificationDeliveryAttempts", "notifications", t =>
                        {
                            t.HasCheckConstraint("CK_NotificationDeliveryAttempts_AttemptNumber", "[AttemptNumber] >= 1");

                            t.HasCheckConstraint("CK_NotificationDeliveryAttempts_Completion", "([Status] IN (1, 2) AND [CompletedAtUtc] IS NULL) OR ([Status] BETWEEN 3 AND 10 AND [CompletedAtUtc] IS NOT NULL)");

                            t.HasCheckConstraint("CK_NotificationDeliveryAttempts_Invocation", "([Status] IN (1, 9, 10) AND [ProviderInvocationStartedAtUtc] IS NULL) OR ([Status] BETWEEN 2 AND 8 AND [ProviderInvocationStartedAtUtc] IS NOT NULL)");

                            t.HasCheckConstraint("CK_NotificationDeliveryAttempts_Status", "[Status] BETWEEN 1 AND 10");
                        });
                });

            modelBuilder.Entity("BotGlobal.Notifications.Domain.NotificationRecipient", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("AttemptCount")
                        .HasColumnType("int");

                    b.Property<Guid>("CampaignId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("CurrentAttemptId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("DeliveryKey")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("DeviceNameSnapshot")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<DateTimeOffset?>("DispatchedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset>("ExpiresAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("InstallationIdSnapshot")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTimeOffset?>("LastAttemptAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("LastSafeErrorCode")
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("LastTransport")
                        .HasMaxLength(32)
                        .IsUnicode(false)
                        .HasColumnType("varchar(32)");

                    b.Property<DateTimeOffset?>("LeaseExpiresAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<Guid?>("LeaseId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("MobileDeviceId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset?>("NextAttemptAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("PlatformSnapshot")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CurrentAttemptId")
                        .IsUnique()
                        .HasDatabaseName("UX_NotificationRecipients_CurrentAttempt")
                        .HasFilter("[CurrentAttemptId] IS NOT NULL");

                    b.HasIndex("DeliveryKey")
                        .IsUnique()
                        .HasDatabaseName("UX_NotificationRecipients_DeliveryKey");

                    b.HasIndex("CampaignId", "MobileDeviceId")
                        .IsUnique()
                        .HasDatabaseName("UX_NotificationRecipients_Campaign_Device");

                    b.HasIndex("Status", "NextAttemptAtUtc", "LeaseExpiresAtUtc")
                        .HasDatabaseName("IX_NotificationRecipients_DispatchWork");

                    b.ToTable("NotificationRecipients", "notifications", t =>
                        {
                            t.HasCheckConstraint("CK_NotificationRecipients_AttemptCount", "[AttemptCount] >= 0");

                            t.HasCheckConstraint("CK_NotificationRecipients_CurrentAttempt", "[Status] IN (1, 2, 7, 10) OR [CurrentAttemptId] IS NOT NULL");

                            t.HasCheckConstraint("CK_NotificationRecipients_Lease", "([LeaseId] IS NULL AND [LeaseExpiresAtUtc] IS NULL) OR ([LeaseId] IS NOT NULL AND [LeaseExpiresAtUtc] IS NOT NULL)");

                            t.HasCheckConstraint("CK_NotificationRecipients_NextAttempt", "([Status] IN (1, 2) AND [NextAttemptAtUtc] IS NOT NULL) OR ([Status] BETWEEN 3 AND 10 AND [NextAttemptAtUtc] IS NULL)");

                            t.HasCheckConstraint("CK_NotificationRecipients_Status", "[Status] BETWEEN 1 AND 10");
                        });
                });

            modelBuilder.Entity("BotGlobal.Notifications.Domain.NotificationDeliveryAttempt", b =>
                {
                    b.HasOne("BotGlobal.Notifications.Domain.NotificationRecipient", "Recipient")
                        .WithMany("DeliveryAttempts")
                        .HasForeignKey("NotificationRecipientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Recipient");
                });

            modelBuilder.Entity("BotGlobal.Notifications.Domain.NotificationRecipient", b =>
                {
                    b.HasOne("BotGlobal.Notifications.Domain.NotificationCampaign", "Campaign")
                        .WithMany()
                        .HasForeignKey("CampaignId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Campaign");
                });

            modelBuilder.Entity("BotGlobal.Notifications.Domain.NotificationRecipient", b =>
                {
                    b.Navigation("DeliveryAttempts");
                });
#pragma warning restore 612, 618
        }
    }
}
