// <auto-generated />
using System;
using BotGlobal.Catalog.Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BotGlobal.Catalog.Infrastructure.Migrations
{
    [DbContext(typeof(CatalogDbContext))]
    [Migration("20261003054913_RefreshSentriCamCatalogContent")]
    partial class RefreshSentriCamCatalogContent
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("catalog")
                .HasAnnotation("ProductVersion", "10.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("BotGlobal.Catalog.Domain.Product", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("varchar(16)");

                    b.Property<bool>("IsFeatured")
                        .HasColumnType("bit");

                    b.Property<string>("PublicationStatus")
                        .IsRequired()
                        .HasColumnType("varchar(16)");

                    b.Property<DateTimeOffset?>("PublishedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("SortOrder")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Category", "Slug")
                        .IsUnique()
                        .HasDatabaseName("UX_Products_Category_Slug");

                    b.ToTable("Products", "catalog", t =>
                        {
                            t.HasCheckConstraint("CK_Products_Category", "[Category] IN ('app', 'game', 'program')");

                            t.HasCheckConstraint("CK_Products_FeaturedPublished", "[IsFeatured] = 0 OR [PublicationStatus] = 'Published'");

                            t.HasCheckConstraint("CK_Products_PublicationStatus", "[PublicationStatus] IN ('Draft', 'Published', 'Archived')");

                            t.HasCheckConstraint("CK_Products_Slug", "LEN([Slug]) > 0 AND [Slug] COLLATE Latin1_General_100_BIN2 = LOWER([Slug]) AND [Slug] NOT LIKE '%[^a-z0-9-]%' AND [Slug] NOT LIKE '-%' AND [Slug] NOT LIKE '%-' AND [Slug] NOT LIKE '%--%'");

                            t.HasCheckConstraint("CK_Products_SortOrder", "[SortOrder] >= 0");
                        });

                    b.HasData(
                        new
                        {
                            Id = new Guid("a5b5930e-8499-4b52-9a76-6cc0de0f4a11"),
                            Category = "app",
                            IsFeatured = true,
                            PublicationStatus = "Published",
                            Slug = "sentricam",
                            SortOrder = 0
                        });
                });

            modelBuilder.Entity("BotGlobal.Catalog.Domain.ProductLink", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("LabelAr")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("LabelEn")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<Guid>("ProductId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("SortOrder")
                        .HasColumnType("int");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("varchar(16)");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasMaxLength(2048)
                        .HasColumnType("nvarchar(2048)");

                    b.Property<byte[]>("UrlHash")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("binary(32)")
                        .HasComputedColumnSql("CONVERT(binary(32), HASHBYTES('SHA2_256', CONVERT(varbinary(max), [Url])))", true);

                    b.HasKey("Id");

                    b.HasIndex("ProductId", "Type", "UrlHash")
                        .IsUnique()
                        .HasDatabaseName("UX_ProductLinks_ProductId_Type_Url");

                    b.ToTable("ProductLinks", "catalog", t =>
                        {
                            t.HasCheckConstraint("CK_ProductLinks_SortOrder", "[SortOrder] >= 0");

                            t.HasCheckConstraint("CK_ProductLinks_Type", "[Type] IN ('support', 'privacy', 'store', 'download', 'website')");
                        });
                });

            modelBuilder.Entity("BotGlobal.Catalog.Domain.ProductLocalization", b =>
                {
                    b.Property<Guid>("ProductId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Language")
                        .HasColumnType("char(2)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DisplayStatus")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Platforms")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("PlatformsJson")
                        .HasDefaultValueSql("N'[]'");

                    b.Property<string>("ShortDescription")
                        .IsRequired()
                        .HasMaxLength(600)
                        .HasColumnType("nvarchar(600)");

                    b.Property<string>("Technologies")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("TechnologiesJson")
                        .HasDefaultValueSql("N'[]'");

                    b.HasKey("ProductId", "Language");

                    b.ToTable("ProductLocalizations", "catalog", t =>
                        {
                            t.HasCheckConstraint("CK_ProductLocalizations_Language", "[Language] IN ('en', 'ar')");

                            t.HasCheckConstraint("CK_ProductLocalizations_PlatformsJson", "ISJSON([PlatformsJson]) = 1 AND LEFT(LTRIM([PlatformsJson]), 1) = '['");

                            t.HasCheckConstraint("CK_ProductLocalizations_TechnologiesJson", "ISJSON([TechnologiesJson]) = 1 AND LEFT(LTRIM([TechnologiesJson]), 1) = '['");
                        });

                    b.HasData(
                        new
                        {
                            ProductId = new Guid("a5b5930e-8499-4b52-9a76-6cc0de0f4a11"),
                            Language = "en",
                            Description = "SentriCam turns Android phones into managed monitoring devices connected to a local Hub on a home or office computer. The setup journey covers Hub installation, storage policy selection, QR pairing, device health, recording control, local recording archive, and LAN live view. The V1 boundary is deliberately local-first: SignalR coordinates authorized sessions, while video stays on the local network and cloud/AI capabilities remain deferred.",
                            DisplayStatus = "V1 runtime showcase",
                            Name = "SentriCam",
                            Platforms = "[\"Android camera device\",\"SentriCam Hub\",\"Browser dashboard\"]",
                            ShortDescription = "Local-first camera monitoring for homes and small teams, pairing Android camera devices with a private Hub and browser dashboard.",
                            Technologies = "[\"Kotlin\",\"CameraX\",\"ASP.NET Core\",\"SignalR\",\"WebRTC LAN live view\"]"
                        },
                        new
                        {
                            ProductId = new Guid("a5b5930e-8499-4b52-9a76-6cc0de0f4a11"),
                            Language = "ar",
                            Description = "يحول SentriCam هواتف أندرويد إلى أجهزة مراقبة مُدارة تتصل بـ Hub محلي على كمبيوتر في المنزل أو المكتب. رحلة الإعداد تشمل تثبيت الـ Hub، اختيار سياسة التخزين، الاقتران عبر QR، متابعة صحة الجهاز، التحكم في التسجيل، أرشيف التسجيلات المحلي، والبث المباشر داخل الشبكة المحلية. حدود V1 مقصودة: SignalR ينسق الجلسات المصرح بها، بينما يظل الفيديو داخل الشبكة المحلية وتبقى إمكانات السحابة والذكاء الاصطناعي مؤجلة.",
                            DisplayStatus = "استعراض تشغيلي V1",
                            Name = "SentriCam",
                            Platforms = "[\"\\u062C\\u0647\\u0627\\u0632 \\u0643\\u0627\\u0645\\u064A\\u0631\\u0627 \\u0623\\u0646\\u062F\\u0631\\u0648\\u064A\\u062F\",\"SentriCam Hub\",\"\\u0644\\u0648\\u062D\\u0629 \\u062A\\u062D\\u0643\\u0645 \\u0627\\u0644\\u0645\\u062A\\u0635\\u0641\\u062D\"]",
                            ShortDescription = "مراقبة كاميرات محلية للمنازل والفرق الصغيرة، تربط أجهزة أندرويد بلوحة Hub خاصة ولوحة تحكم من المتصفح.",
                            Technologies = "[\"Kotlin\",\"CameraX\",\"ASP.NET Core\",\"SignalR\",\"\\u0628\\u062B \\u0645\\u0628\\u0627\\u0634\\u0631 WebRTC \\u062F\\u0627\\u062E\\u0644 \\u0627\\u0644\\u0634\\u0628\\u0643\\u0629 \\u0627\\u0644\\u0645\\u062D\\u0644\\u064A\\u0629\"]"
                        });
                });

            modelBuilder.Entity("BotGlobal.Catalog.Domain.ProductMedia", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("AltTextAr")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<string>("AltTextEn")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<long?>("ByteLength")
                        .HasColumnType("bigint");

                    b.Property<string>("ContentType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int?>("Height")
                        .HasColumnType("int");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasColumnType("varchar(16)");

                    b.Property<Guid>("ProductId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("SortOrder")
                        .HasColumnType("int");

                    b.Property<string>("StorageKey")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("StorageProvider")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.Property<int?>("Width")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ProductId")
                        .IsUnique()
                        .HasDatabaseName("UX_ProductMedia_ProductId_Hero")
                        .HasFilter("[Kind] = 'hero'");

                    b.HasIndex("StorageProvider", "StorageKey")
                        .IsUnique()
                        .HasDatabaseName("UX_ProductMedia_StorageProvider_StorageKey");

                    b.ToTable("ProductMedia", "catalog", t =>
                        {
                            t.HasCheckConstraint("CK_ProductMedia_ByteLength", "[ByteLength] IS NULL OR [ByteLength] >= 0");

                            t.HasCheckConstraint("CK_ProductMedia_Height", "[Height] IS NULL OR [Height] > 0");

                            t.HasCheckConstraint("CK_ProductMedia_Kind", "[Kind] IN ('hero', 'screenshot')");

                            t.HasCheckConstraint("CK_ProductMedia_SortOrder", "[SortOrder] >= 0");

                            t.HasCheckConstraint("CK_ProductMedia_Width", "[Width] IS NULL OR [Width] > 0");
                        });
                });

            modelBuilder.Entity("BotGlobal.Catalog.Domain.ProductRelease", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("NotesAr")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NotesEn")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("ProductId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("PublicationStatus")
                        .IsRequired()
                        .HasColumnType("varchar(16)");

                    b.Property<DateTimeOffset?>("ReleasedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<int>("SortOrder")
                        .HasColumnType("int");

                    b.Property<string>("Version")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.HasKey("Id");

                    b.HasIndex("ProductId", "Version")
                        .IsUnique()
                        .HasDatabaseName("UX_ProductReleases_ProductId_Version");

                    b.ToTable("ProductReleases", "catalog", t =>
                        {
                            t.HasCheckConstraint("CK_ProductReleases_PublicationStatus", "[PublicationStatus] IN ('Draft', 'Published', 'Archived')");

                            t.HasCheckConstraint("CK_ProductReleases_SortOrder", "[SortOrder] >= 0");
                        });
                });

            modelBuilder.Entity("BotGlobal.Catalog.Domain.ProductLink", b =>
                {
                    b.HasOne("BotGlobal.Catalog.Domain.Product", null)
                        .WithMany("Links")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("BotGlobal.Catalog.Domain.ProductLocalization", b =>
                {
                    b.HasOne("BotGlobal.Catalog.Domain.Product", null)
                        .WithMany("Localizations")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("BotGlobal.Catalog.Domain.ProductMedia", b =>
                {
                    b.HasOne("BotGlobal.Catalog.Domain.Product", null)
                        .WithMany("Media")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("BotGlobal.Catalog.Domain.ProductRelease", b =>
                {
                    b.HasOne("BotGlobal.Catalog.Domain.Product", null)
                        .WithMany("Releases")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("BotGlobal.Catalog.Domain.Product", b =>
                {
                    b.Navigation("Links");

                    b.Navigation("Localizations");

                    b.Navigation("Media");

                    b.Navigation("Releases");
                });
#pragma warning restore 612, 618
        }
    }
}
