// <auto-generated />
using System;
using BotGlobal.Catalog.Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BotGlobal.Catalog.Infrastructure.Migrations
{
    [DbContext(typeof(CatalogDbContext))]
    partial class CatalogDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("catalog")
                .HasAnnotation("ProductVersion", "10.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("BotGlobal.Catalog.Domain.Product", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("varchar(16)");

                    b.Property<bool>("IsFeatured")
                        .HasColumnType("bit");

                    b.Property<string>("PublicationStatus")
                        .IsRequired()
                        .HasColumnType("varchar(16)");

                    b.Property<DateTimeOffset?>("PublishedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("SortOrder")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Category", "Slug")
                        .IsUnique()
                        .HasDatabaseName("UX_Products_Category_Slug");

                    b.ToTable("Products", "catalog", t =>
                        {
                            t.HasCheckConstraint("CK_Products_Category", "[Category] IN ('app', 'game', 'program')");

                            t.HasCheckConstraint("CK_Products_FeaturedPublished", "[IsFeatured] = 0 OR [PublicationStatus] = 'Published'");

                            t.HasCheckConstraint("CK_Products_PublicationStatus", "[PublicationStatus] IN ('Draft', 'Published', 'Archived')");

                                    t.HasCheckConstraint("CK_Products_Slug", "LEN([Slug]) > 0 AND [Slug] COLLATE Latin1_General_100_BIN2 = LOWER([Slug]) AND [Slug] NOT LIKE '%[^a-z0-9-]%' AND [Slug] NOT LIKE '-%' AND [Slug] NOT LIKE '%-' AND [Slug] NOT LIKE '%--%'");

                            t.HasCheckConstraint("CK_Products_SortOrder", "[SortOrder] >= 0");
                        });

                    b.HasData(
                        new
                        {
                            Id = new Guid("a5b5930e-8499-4b52-9a76-6cc0de0f4a11"),
                            Category = "app",
                            IsFeatured = true,
                            PublicationStatus = "Published",
                            Slug = "sentricam",
                            SortOrder = 0
                        });
                });

            modelBuilder.Entity("BotGlobal.Catalog.Domain.ProductLink", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("LabelAr")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("LabelEn")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<Guid>("ProductId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("SortOrder")
                        .HasColumnType("int");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("varchar(16)");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasMaxLength(2048)
                        .HasColumnType("nvarchar(2048)");

                    b.Property<byte[]>("UrlHash")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("binary(32)")
                        .HasComputedColumnSql("CONVERT(binary(32), HASHBYTES('SHA2_256', CONVERT(varbinary(max), [Url])))", true);

                    b.HasKey("Id");

                    b.HasIndex("ProductId", "Type", "UrlHash")
                        .IsUnique()
                        .HasDatabaseName("UX_ProductLinks_ProductId_Type_Url")
                        ;

                    b.ToTable("ProductLinks", "catalog", t =>
                        {
                            t.HasCheckConstraint("CK_ProductLinks_SortOrder", "[SortOrder] >= 0");

                            t.HasCheckConstraint("CK_ProductLinks_Type", "[Type] IN ('support', 'privacy', 'store', 'download', 'website')");
                        });
                });

            modelBuilder.Entity("BotGlobal.Catalog.Domain.ProductLocalization", b =>
                {
                    b.Property<Guid>("ProductId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Language")
                        .HasColumnType("char(2)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DisplayStatus")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Platforms")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("PlatformsJson")
                        .HasDefaultValueSql("N'[]'");

                    b.Property<string>("ShortDescription")
                        .IsRequired()
                        .HasMaxLength(600)
                        .HasColumnType("nvarchar(600)");

                    b.Property<string>("Technologies")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("TechnologiesJson")
                        .HasDefaultValueSql("N'[]'");

                    b.HasKey("ProductId", "Language");

                    b.ToTable("ProductLocalizations", "catalog", t =>
                        {
                            t.HasCheckConstraint("CK_ProductLocalizations_Language", "[Language] IN ('en', 'ar')");

                            t.HasCheckConstraint("CK_ProductLocalizations_PlatformsJson", "ISJSON([PlatformsJson]) = 1 AND LEFT(LTRIM([PlatformsJson]), 1) = '['");

                            t.HasCheckConstraint("CK_ProductLocalizations_TechnologiesJson", "ISJSON([TechnologiesJson]) = 1 AND LEFT(LTRIM([TechnologiesJson]), 1) = '['");
                        });

                    b.HasData(
                        new
                        {
                            ProductId = new Guid("a5b5930e-8499-4b52-9a76-6cc0de0f4a11"),
                            Language = "en",
                            Description = "SentriCam is identified in the BOT GLOBAL platform documentation as an existing product. Verified public feature, platform, media, availability, and support details have not yet been published, so this entry intentionally makes no additional product claims.",
                            DisplayStatus = "Details pending",
                            Name = "SentriCam",
                            Platforms = "[]",
                            ShortDescription = "An existing BOT GLOBAL product with public catalog details in preparation.",
                            Technologies = "[]"
                        },
                        new
                        {
                            ProductId = new Guid("a5b5930e-8499-4b52-9a76-6cc0de0f4a11"),
                            Language = "ar",
                            Description = "تُعرّف وثائق منصة BOT GLOBAL منتج SentriCam باعتباره منتجًا قائمًا. لم تُنشر بعد تفاصيل موثقة للعامة حول الميزات أو المنصات أو الوسائط أو الإتاحة أو الدعم؛ لذلك لا يتضمن هذا السجل أي ادعاءات إضافية عن المنتج.",
                            DisplayStatus = "التفاصيل قيد الإعداد",
                            Name = "SentriCam",
                            Platforms = "[]",
                            ShortDescription = "منتج قائم من BOT GLOBAL، ويجري حاليًا إعداد تفاصيله للنشر في الكتالوج العام.",
                            Technologies = "[]"
                        });
                });

            modelBuilder.Entity("BotGlobal.Catalog.Domain.ProductMedia", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("AltTextAr")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<string>("AltTextEn")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<long?>("ByteLength")
                        .HasColumnType("bigint");

                    b.Property<string>("ContentType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int?>("Height")
                        .HasColumnType("int");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasColumnType("varchar(16)");

                    b.Property<Guid>("ProductId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("SortOrder")
                        .HasColumnType("int");

                    b.Property<string>("StorageKey")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("StorageProvider")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.Property<int?>("Width")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ProductId")
                        .IsUnique()
                        .HasDatabaseName("UX_ProductMedia_ProductId_Hero")
                        .HasFilter("[Kind] = 'hero'");

                    b.HasIndex("StorageProvider", "StorageKey")
                        .IsUnique()
                        .HasDatabaseName("UX_ProductMedia_StorageProvider_StorageKey");

                    b.ToTable("ProductMedia", "catalog", t =>
                        {
                            t.HasCheckConstraint("CK_ProductMedia_ByteLength", "[ByteLength] IS NULL OR [ByteLength] >= 0");

                            t.HasCheckConstraint("CK_ProductMedia_Height", "[Height] IS NULL OR [Height] > 0");

                            t.HasCheckConstraint("CK_ProductMedia_Kind", "[Kind] IN ('hero', 'screenshot')");

                            t.HasCheckConstraint("CK_ProductMedia_SortOrder", "[SortOrder] >= 0");

                            t.HasCheckConstraint("CK_ProductMedia_Width", "[Width] IS NULL OR [Width] > 0");
                        });
                });

            modelBuilder.Entity("BotGlobal.Catalog.Domain.ProductRelease", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("NotesAr")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NotesEn")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("ProductId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("PublicationStatus")
                        .IsRequired()
                        .HasColumnType("varchar(16)");

                    b.Property<DateTimeOffset?>("ReleasedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<int>("SortOrder")
                        .HasColumnType("int");

                    b.Property<string>("Version")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.HasKey("Id");

                    b.HasIndex("ProductId", "Version")
                        .IsUnique()
                        .HasDatabaseName("UX_ProductReleases_ProductId_Version");

                    b.ToTable("ProductReleases", "catalog", t =>
                        {
                            t.HasCheckConstraint("CK_ProductReleases_PublicationStatus", "[PublicationStatus] IN ('Draft', 'Published', 'Archived')");

                            t.HasCheckConstraint("CK_ProductReleases_SortOrder", "[SortOrder] >= 0");
                        });
                });

            modelBuilder.Entity("BotGlobal.Catalog.Domain.ProductLink", b =>
                {
                    b.HasOne("BotGlobal.Catalog.Domain.Product", null)
                        .WithMany("Links")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("BotGlobal.Catalog.Domain.ProductLocalization", b =>
                {
                    b.HasOne("BotGlobal.Catalog.Domain.Product", null)
                        .WithMany("Localizations")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("BotGlobal.Catalog.Domain.ProductMedia", b =>
                {
                    b.HasOne("BotGlobal.Catalog.Domain.Product", null)
                        .WithMany("Media")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("BotGlobal.Catalog.Domain.ProductRelease", b =>
                {
                    b.HasOne("BotGlobal.Catalog.Domain.Product", null)
                        .WithMany("Releases")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("BotGlobal.Catalog.Domain.Product", b =>
                {
                    b.Navigation("Links");

                    b.Navigation("Localizations");

                    b.Navigation("Media");

                    b.Navigation("Releases");
                });
#pragma warning restore 612, 618
        }
    }
}
