<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <NoWarn>$(NoWarn);CA1825;CA1861</NoWarn>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\SentriCam.Infrastructure\SentriCam.Infrastructure.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="Npgsql.EntityFrameworkCore.PostgreSQL" />
  </ItemGroup>

</Project>
