package com.botglobal.nqrb.app.ui

data class NqrbStrings(
    val productName: String, val productNameArabic: String,
    val heroEyebrow: String, val heroTitle: String, val heroBody: String,
    val foundationStatus: String, val foundationStatusBody: String,
    val primaryCallTitle: String, val primaryCallBody: String,
    val madarGreeting: String, val madarCircleHint: String,
    val madarInviteTitle: String, val madarInviteBody: String,
    val createCallLinkTitle: String, val createCallLinkBody: String,
    val home: String, val history: String, val notifications: String, val people: String, val profile: String, val settings: String,
    val call: String, val openSettings: String, val back: String,
    val language: String, val appearance: String, val arabic: String, val english: String,
    val system: String, val light: String, val dark: String,
    val privacyAndSupport: String, val privacyPolicy: String,
    val accountDeletionHelp: String, val support: String,
    val historyTitle: String, val historyBody: String,
    val notificationInboxTitle: String, val notificationInboxBody: String, val notificationInboxEmpty: String,
    val peopleTitle: String, val peopleBody: String,
    val profileTitle: String, val profileBody: String, val selected: String,
    val accountInformation: String, val accountName: String, val emailAddress: String,
    val unavailableAccountName: String, val unavailableAccountEmail: String,
    val accountIdentityLoading: String, val accountIdentityError: String,
    val signInTitle: String, val signInBody: String, val restoringTitle: String, val restoringBody: String,
    val updateRequiredTitle: String, val updateRequiredBody: String, val updateNow: String,
    val continueWithGoogle: String,
    val googleConfigurationMissing: String, val googleUnavailable: String, val googleSignInFailed: String,
    val googleRejected: String, val accountLinkRequired: String, val networkFailure: String, val signInPrivacy: String,
    val logout: String,
    val deleteAccount: String, val deleteAccountSummary: String,
    val deleteAccountFirstTitle: String, val deleteAccountFirstBody: String, val continueToDelete: String,
    val deleteAccountFinalTitle: String, val deleteAccountFinalBody: String, val confirmDeleteAccount: String,
    val accountDeletionInProgress: String, val accountDeletionFailed: String, val signOutFailed: String,
    val startCall: String, val callablePeopleTitle: String, val callingDirectoryLoading: String,
    val callingDirectoryEmpty: String, val callingDirectoryError: String, val refreshCallingDirectory: String,
    val savedContactsTitle: String, val savedContactsBody: String, val savedContactsLoading: String,
    val savedContactsEmpty: String, val savedContactsError: String, val loadMoreContacts: String,
    val searchNqrbUsers: String, val loadMoreSearchResults: String,
    val searchPlaceholder: String, val addContact: String, val removeContact: String,
    val contactSearchTooShort: String, val contactSearchEmpty: String, val contactSearchError: String,
    val inviteContactsTitle: String, val inviteContactsBody: String, val createInvite: String,
    val creatingInvite: String, val inviteCode: String, val inviteShareLink: String,
    val copyInvite: String, val inviteCopied: String, val shareInvite: String,
    val copyInviteCode: String, val shareInviteUnavailable: String, val inviteShareMessage: String,
    val acceptInviteTitle: String,
    val inviteCodePlaceholder: String, val previewInvite: String, val acceptInvite: String,
    val invitePreviewBody: String, val inviteAccepted: String, val inviteInvalid: String,
    val inviteExpired: String, val inviteSelf: String, val inviteClaimed: String, val inviteError: String,
    val retry: String, val microphoneTitle: String, val microphoneBody: String,
    val continueCall: String, val browseDuringCall: String, val returnToCall: String,
    val cancel: String, val connecting: String, val ringing: String,
    val activeCall: String, val reconnecting: String, val endingCall: String, val callFailed: String,
    val mute: String, val unmute: String, val speaker: String, val earpiece: String, val audioRoute: String,
    val endCall: String,
    val answerCall: String, val declineCall: String, val microphoneDenied: String,
    val onlineNow: String, val availableForCalls: String, val currentlyUnavailable: String,
    val historyLoading: String, val historyEmpty: String, val historyError: String, val loadMore: String,
    val allCalls: String, val addFromHistory: String, val contactAdded: String, val contactAddUnavailable: String,
    val guestHistory: String,
    val incoming: String, val outgoing: String, val completed: String, val rejected: String,
    val missed: String, val cancelled: String, val expired: String, val failed: String,
    val callTime: String, val ringingDuration: String, val connectedDuration: String, val dataUsage: String,
    val currentPeriod: String, val from: String, val sent: String, val received: String,
    val total: String, val averagePerMinute: String, val resetUsage: String,
    val resetUsageConfirmation: String, val confirmResetUsage: String,
    val ringtoneTitle: String, val ringtoneBody: String, val ringtoneMadar: String,
    val ringtoneGentle: String, val ringtoneClassic: String, val ringtoneClear: String,
    val ringtonePulse: String, val ringtoneDevice: String, val choosePhoneRingtone: String, val previewRingtone: String,
    val guestCallLinkTitle: String, val guestCallLinkBody: String,
    val guestCallCreate: String, val guestCallStartWait: String, val guestCallWaitBody: String,
    val guestCallWaitingTitle: String, val guestCallWaitingInstruction: String,
    val guestCallLinkReady: String,
    val guestCallExpiresAt: String,
    val guestCallExpired: String,
    val guestCallCopyLink: String, val guestCallShare: String, val guestCallShareUnavailable: String,
    val swipeToCallHint: String, val contactActions: String,
    val editContactNickname: String, val nicknameHint: String, val nicknameOriginal: String,
    val saveNickname: String, val nicknameError: String,
    val blockedTitle: String, val blockedBody: String, val blockContact: String,
    val unblockContact: String, val blockConfirmTitle: String, val blockConfirmBody: String,
    val blockError: String, val blockedLabel: String, val blockedLoadError: String,
    val clearSearch: String, val showDetails: String, val hideDetails: String,
    val notificationsTitle: String, val notificationsDisabledBody: String, val openNotificationSettings: String,
    val appVersion: String,
)

fun nqrbStrings(languageTag: String): NqrbStrings = if (languageTag.startsWith("ar")) ArabicStrings else EnglishStrings

private val ArabicStrings = NqrbStrings(
    productName = "Nqrb", productNameArabic = "نقرب", heroEyebrow = "صوت يجمعنا",
    heroTitle = "أقرب، أينما كنتم", heroBody = "تجربة اتصال صوتي صُممت لتكون واضحة، هادئة، وإنسانية.",
    foundationStatus = "اتصال آمن", foundationStatusBody = "الهوية والمكالمات وسجل نشاط الاتصال تعمل ضمن حسابك في نقرب.",
    primaryCallTitle = "اتصال مباشر", primaryCallBody = "مكان بسيط لاتصال صوتي بين شخصين.",
    madarGreeting = "أهلًا بك من جديد",
    madarCircleHint = "اختر شخصًا من دائرتك لبدء مكالمة", madarInviteTitle = "وسّع دائرتك",
    madarInviteBody = "شارك دعوتك؛ تنضمّان إلى قائمة بعضكما.",
    createCallLinkTitle = "أنشئ رابط اتصال", createCallLinkBody = "شارك دعوة خاصة للانضمام لاحقًا من التطبيق أو المتصفح.",
    home = "الرئيسية", history = "السجل", notifications = "الإشعارات", people = "الأشخاص", profile = "حسابي", settings = "الإعدادات",
    call = "اتصال", openSettings = "فتح الإعدادات", back = "رجوع", language = "اللغة", appearance = "المظهر",
    arabic = "العربية", english = "English", system = "النظام", light = "فاتح", dark = "داكن",
    privacyAndSupport = "الخصوصية والدعم", privacyPolicy = "سياسة الخصوصية",
    accountDeletionHelp = "معلومات حذف الحساب", support = "دعم NQRB",
    historyTitle = "سجل الاتصالات", historyBody = "راجع مكالماتك ومدة الاتصال واستخدام البيانات.",
    notificationInboxTitle = "الإشعارات", notificationInboxBody = "كل تنبيهات نقرب المهمة في مكان واحد.",
    notificationInboxEmpty = "لا توجد إشعارات حتى الآن.",
    peopleTitle = "دائرتك الخاصة", peopleBody = "ابحث عن حسابات نقرب أو شارك دعوة لتقريب من تحب.",
    profileTitle = "مساحتك في نقرب", profileBody = "حسابك، دائرتك، وطريقة تواصلك.", selected = "محدد",
    accountInformation = "معلومات الحساب", accountName = "اسم الحساب", emailAddress = "البريد الإلكتروني",
    unavailableAccountName = "مستخدم نقرب", unavailableAccountEmail = "غير متاح",
    accountIdentityLoading = "جارٍ تحميل معلومات حسابك...",
    accountIdentityError = "تعذّر تحميل معلومات الحساب. تحقق من الشبكة وحاول مرة أخرى.",
    signInTitle = "خليك قريب.", signInBody = "سجّل دخولك وابدأ تجربتك على نقرب.",
    restoringTitle = "جارٍ استعادة جلستك", restoringBody = "لحظات ونكمل من حيث توقفت بأمان.",
    updateRequiredTitle = "حدّث نقرب للمتابعة",
    updateRequiredBody = "هذا الإصدار لم يعد مدعومًا. حدّث التطبيق من المتجر لاستخدام نقرب.",
    updateNow = "تحديث التطبيق",
    continueWithGoogle = "المتابعة باستخدام Google",
    googleConfigurationMissing = "تسجيل الدخول عبر Google غير مهيأ في هذا الإصدار. لم يتم تسجيل دخولك.",
    googleUnavailable = "تعذّر فتح اختيار حساب Google على هذا الجهاز.",
    googleSignInFailed = "تعذّر إكمال تسجيل الدخول. حاول مرة أخرى.",
    googleRejected = "لم يقبل الخادم بيانات تسجيل الدخول.",
    accountLinkRequired = "يوجد حساب بهذا البريد ويحتاج إلى ربط آمن قبل المتابعة.",
    networkFailure = "تعذّر الاتصال بالخادم. تحقق من الشبكة وحاول مرة أخرى.",
    signInPrivacy = "نستخدم بيانات Google لمرة واحدة لإثبات هويتك، ثم يحفظ نقرب جلسة المنصة الآمنة فقط.",
    logout = "تسجيل الخروج",
    deleteAccount = "حذف الحساب", deleteAccountSummary = "احذف حسابك وبياناتك المرتبطة بنقرب نهائيًا.",
    deleteAccountFirstTitle = "حذف حساب نقرب؟",
    deleteAccountFirstBody = "هذا الإجراء دائم. سيتم تسجيل خروجك، ولن تعمل أجهزتك المقترنة أو إشعارات نقرب بعد الحذف.",
    continueToDelete = "متابعة الحذف", deleteAccountFinalTitle = "تأكيد الحذف النهائي",
    deleteAccountFinalBody = "لن تتمكن من استعادة حساب نقرب أو سجل مكالماتك بعد التأكيد. اضغط حذف الحساب فقط إذا كنت متأكدًا.",
    confirmDeleteAccount = "حذف الحساب نهائيًا", accountDeletionInProgress = "جارٍ حذف حسابك وتأمين تسجيل الخروج…",
    accountDeletionFailed = "تعذّر إكمال حذف الحساب بأمان. لم نمسح بيانات الدخول اللازمة لإعادة المحاولة.",
    signOutFailed = "تعذّر إلغاء اقتران الجهاز. ما زلت مسجّلًا ويمكنك المحاولة مرة أخرى.",
    startCall = "بدء مكالمة نقرب", callablePeopleTitle = "الأشخاص في دائرتك",
    callingDirectoryLoading = "جاري تحميل جهاتك المحفوظة...",
    callingDirectoryEmpty = "قائمتك فارغة. أضف أشخاصًا من شاشة الأشخاص.",
    callingDirectoryError = "تعذر تحميل جهات الاتصال المحفوظة. حاول مرة أخرى.",
    refreshCallingDirectory = "تحديث الجهات",
    savedContactsTitle = "دائرتي", savedContactsBody = "قائمة خاصة بحسابك؛ أنت تختار من تحتفظ به.",
    savedContactsLoading = "جارٍ تحميل جهاتك المحفوظة...", savedContactsEmpty = "لم تضف أي جهة بعد.",
    savedContactsError = "تعذر تحميل جهاتك. حاول مرة أخرى.", loadMoreContacts = "عرض المزيد من جهاتي",
    searchNqrbUsers = "البحث في حسابات نقرب", loadMoreSearchResults = "عرض نتائج أخرى",
    searchPlaceholder = "اكتب حرفين على الأقل", addContact = "إضافة", removeContact = "إزالة",
    contactSearchTooShort = "اكتب حرفين على الأقل للبحث.", contactSearchEmpty = "لا توجد نتائج مطابقة.",
    contactSearchError = "تعذر إكمال البحث. حاول مرة أخرى.",
    inviteContactsTitle = "شارك حسابك بسهولة", inviteContactsBody = "دعوة واحدة تضيفكما إلى دائرة بعضكما. ويمكن لصديقك إدخال الكود يدويًا.",
    createInvite = "إنشاء رمز دعوة", creatingInvite = "جارٍ إنشاء الرمز...", inviteCode = "رمز الدعوة",
    inviteShareLink = "رابط المشاركة", copyInvite = "نسخ الدعوة", inviteCopied = "تم النسخ.",
    shareInvite = "مشاركة حسابي", copyInviteCode = "نسخ الكود",
    shareInviteUnavailable = "تعذّر فتح المشاركة. انسخ الكود وأرسله لمن تريد.",
    inviteShareMessage = "أضفني على نقرب. افتح التطبيق واختر الأشخاص ← قبول دعوة، ثم أدخل الكود: %s\nرابط فتح التطبيق: %s",
    acceptInviteTitle = "قبول دعوة", inviteCodePlaceholder = "الصق الرمز أو رابط الدعوة",
    previewInvite = "معاينة الدعوة", acceptInvite = "قبول وإضافة الطرفين",
    invitePreviewBody = "سيتم إضافة %s إلى جهاتك، وستظهر أنت أيضًا في جهاته.",
    inviteAccepted = "تم قبول الدعوة وإضافة الجهتين.", inviteInvalid = "رمز الدعوة غير صحيح أو غير متاح.",
    inviteExpired = "انتهت صلاحية هذه الدعوة.", inviteSelf = "لا يمكنك قبول دعوتك الخاصة.",
    inviteClaimed = "تم استخدام هذه الدعوة من قبل.", inviteError = "تعذرت معالجة الدعوة. حاول مرة أخرى.",
    retry = "حاول مرة أخرى",
    microphoneTitle = "استخدام الميكروفون أثناء المكالمة",
    microphoneBody = "يحتاج نقرب إلى الميكروفون لإرسال صوتك، وإلى إظهار حالة المكالمة الجارية على نظام Android.",
    continueCall = "متابعة المكالمة", browseDuringCall = "تصفح التطبيق أثناء المكالمة", returnToCall = "العودة للمكالمة",
    cancel = "إلغاء", connecting = "جارٍ الاتصال", ringing = "في انتظار الرد",
    activeCall = "مكالمة جارية", reconnecting = "جارٍ استعادة الاتصال", endingCall = "جارٍ إنهاء المكالمة",
    callFailed = "تعذّر بدء المكالمة", mute = "كتم", unmute = "إلغاء الكتم", speaker = "مكبر الصوت",
    earpiece = "سماعة الهاتف", audioRoute = "مسار الصوت", endCall = "إنهاء المكالمة", answerCall = "رد", declineCall = "رفض",
    microphoneDenied = "لم يبدأ الاتصال لأن إذن الميكروفون غير متاح. يمكنك المحاولة مجددًا بعد تمكينه.",
    onlineNow = "متصل الآن", availableForCalls = "متاح للمكالمات", currentlyUnavailable = "غير متاح حاليًا",
    historyLoading = "جارٍ تحميل سجل الاتصالات...", historyEmpty = "لا توجد اتصالات مسجلة بعد.",
    historyError = "تعذر تحميل سجل الاتصالات. حاول مرة أخرى.", loadMore = "تحميل مكالمات أقدم",
    allCalls = "الكل", addFromHistory = "إضافة لجهات الاتصال", contactAdded = "تمت إضافة جهة الاتصال.",
    contactAddUnavailable = "لا يمكن إضافة هذا الطرف إلى جهات نقرب.",
    guestHistory = "ضيف عبر الرابط",
    incoming = "واردة", outgoing = "صادرة",
    completed = "مكتملة", rejected = "مرفوضة", missed = "فائتة", cancelled = "ملغاة", expired = "انتهت المهلة", failed = "فشلت",
    callTime = "وقت الاتصال", ringingDuration = "مدة الرنين", connectedDuration = "مدة الاتصال", dataUsage = "استخدام البيانات",
    currentPeriod = "الفترة الحالية", from = "منذ", sent = "مرسل", received = "مستقبل", total = "الإجمالي",
    averagePerMinute = "لكل دقيقة اتصال", resetUsage = "بدء فترة استخدام جديدة",
    resetUsageConfirmation = "سيبدأ العداد من الصفر، ولن يتغير استخدام المكالمات السابقة.",
    confirmResetUsage = "تأكيد بدء فترة جديدة",
    ringtoneTitle = "نغمة المكالمات الواردة", ringtoneBody = "اختر النغمة التي تسمعها عندما يتصل بك أحد على نقرب.",
    ringtoneMadar = "مدار · الافتراضية", ringtoneGentle = "هادئة", ringtoneClassic = "كلاسيكية",
    ringtoneClear = "واضحة · صوت أعلى", ringtonePulse = "نبض · صوت أعلى",
    ringtoneDevice = "نغمة من الهاتف", choosePhoneRingtone = "اختر نغمة الهاتف",
    previewRingtone = "استماع",
    guestCallLinkTitle = "رابط مكالمة ضيف",
    guestCallLinkBody = "أنشئ رابطًا مؤقتًا لشخص واحد. الضيف يبدأ من المتصفح، وسيصلك تنبيه عندما ينضم حتى لو لم تكن على شاشة الانتظار. ينتهي الرابط قريبًا، والاتصال مجاني بمحاولة مباشرة وقد يفشل على بعض الشبكات.",
    guestCallCreate = "ابدأ مكالمة ضيف",
    guestCallStartWait = "ابدأ وانتظر",
    guestCallWaitBody = "ابقَ على شاشة المكالمة لترد بسرعة عندما يبدأ الضيف. إذا غادرت، سيظل نقرب ينبهك عند انضمامه.",
    guestCallWaitingTitle = "في انتظار الضيف",
    guestCallWaitingInstruction = "أرسل الرابط للضيف واطلب منه فتحه وبدء المكالمة من المتصفح. سيظهر تنبيه المكالمة هنا عندما ينضم.",
    guestCallLinkReady = "الرابط جاهز للمشاركة مع ضيف واحد",
    guestCallExpiresAt = "ينتهي الرابط: %s",
    guestCallExpired = "انتهت صلاحية رابط المكالمة. أنشئ رابطًا جديدًا قبل مشاركته.",
    guestCallCopyLink = "نسخ الرابط",
    guestCallShare = "مشاركة الرابط",
    guestCallShareUnavailable = "تعذّرت المشاركة. انسخ رابط المكالمة وأرسله بنفسك.",
    swipeToCallHint = "اسحب البطاقة يمينًا للاتصال، أو اضغط أيقونة الهاتف.",
    editContactNickname = "اسم خاص عندي", nicknameHint = "الاسم الذي يظهر لك وحدك",
    nicknameOriginal = "حساب نقرب: %s", saveNickname = "حفظ الاسم",
    nicknameError = "تعذّر حفظ الاسم. حاول مرة أخرى.",
    contactActions = "إجراءات الجهة",
    blockedTitle = "الحسابات المحظورة", blockedBody = "لن تصلك مكالماتهم أو تنبيهاتهم. يمكنك فك الحظر في أي وقت.",
    blockContact = "حظر الحساب", unblockContact = "فك الحظر", blockConfirmTitle = "حظر هذا الحساب؟",
    blockConfirmBody = "لن تصلك مكالماته أو تنبيهاته، وسيظهر له أنك غير متاح. سيبقى في قائمتك حتى تحذفه.",
    blockError = "تعذّر تحديث الحظر. تحقق من الاتصال وحاول مرة أخرى.", blockedLabel = "محظور",
    blockedLoadError = "تعذّر تحميل قائمة المحظورين. حاول مرة أخرى.",
    clearSearch = "مسح البحث", showDetails = "عرض التفاصيل", hideDetails = "إخفاء التفاصيل",
    notificationsTitle = "تنبيهات المكالمات", notificationsDisabledBody = "إشعارات نقرب متوقفة على هذا الهاتف. فعّلها من إعدادات الهاتف لاستقبال رنين المكالمات والتطبيق مغلق.",
    openNotificationSettings = "فتح إعدادات الإشعارات",
    appVersion = "إصدار التطبيق",
)

private val EnglishStrings = NqrbStrings(
    productName = "Nqrb", productNameArabic = "نقرب", heroEyebrow = "VOICE THAT BRINGS US CLOSER",
    heroTitle = "Closer, wherever you are", heroBody = "A voice experience designed to feel clear, calm, and human.",
    foundationStatus = "Secure calling", foundationStatusBody = "Identity, calls, and communication activity stay scoped to your NQRB account.",
    primaryCallTitle = "Direct call", primaryCallBody = "A focused place for a premium one-to-one voice conversation.",
    madarGreeting = "Welcome back",
    madarCircleHint = "Choose someone in your circle to call", madarInviteTitle = "Grow your circle",
    madarInviteBody = "Share an invite to add each other.",
    createCallLinkTitle = "Create a call link", createCallLinkBody = "Share a private invitation to join later from the app or browser.",
    home = "Home", history = "History", notifications = "Alerts", people = "People", profile = "Profile", settings = "Settings", call = "Call",
    openSettings = "Open settings", back = "Back", language = "Language", appearance = "Appearance",
    arabic = "العربية", english = "English", system = "System", light = "Light", dark = "Dark",
    privacyAndSupport = "Privacy and support", privacyPolicy = "Privacy Policy",
    accountDeletionHelp = "Account deletion information", support = "NQRB support",
    historyTitle = "Call history", historyBody = "Review your calls, connected time, and media data usage.",
    notificationInboxTitle = "Alerts", notificationInboxBody = "Important Nqrb updates in one place.",
    notificationInboxEmpty = "No alerts yet.",
    peopleTitle = "Your private circle", peopleBody = "Find Nqrb accounts or share an invite to connect with someone.",
    profileTitle = "Your space on Nqrb", profileBody = "Your account, circle, and way to connect.", selected = "Selected",
    accountInformation = "Account information", accountName = "Account name", emailAddress = "Email address",
    unavailableAccountName = "NQRB user", unavailableAccountEmail = "Unavailable",
    accountIdentityLoading = "Loading your account information...",
    accountIdentityError = "Account information could not be loaded. Check your connection and try again.",
    signInTitle = "Stay close.", signInBody = "Sign in and get started with NQRB.",
    restoringTitle = "Restoring your session", restoringBody = "One moment while NQRB securely picks up where you left off.",
    updateRequiredTitle = "Update Nqrb to continue",
    updateRequiredBody = "This version is no longer supported. Update the app from the store to keep using Nqrb.",
    updateNow = "Update app",
    continueWithGoogle = "Continue with Google",
    googleConfigurationMissing = "Google sign-in is not configured in this build. You have not been signed in.",
    googleUnavailable = "Google account selection is unavailable on this device.",
    googleSignInFailed = "Sign-in could not be completed. Please try again.",
    googleRejected = "The server did not accept this sign-in credential.",
    accountLinkRequired = "An account with this email exists and requires secure linking before you can continue.",
    networkFailure = "The server could not be reached. Check your connection and try again.",
    signInPrivacy = "Google data is used once to prove your identity; NQRB then stores only the secure platform session.",
    logout = "Sign out",
    deleteAccount = "Delete account", deleteAccountSummary = "Permanently delete your NQRB account and associated data.",
    deleteAccountFirstTitle = "Delete your NQRB account?",
    deleteAccountFirstBody = "This action is permanent. You will be signed out, and your paired devices and NQRB notifications will stop working.",
    continueToDelete = "Continue to deletion", deleteAccountFinalTitle = "Final deletion confirmation",
    deleteAccountFinalBody = "You cannot recover your NQRB account or call history after confirming. Select Delete account only if you are sure.",
    confirmDeleteAccount = "Delete account permanently", accountDeletionInProgress = "Deleting your account and signing you out securely…",
    accountDeletionFailed = "Account deletion could not be completed safely. Sign-in data needed to retry has not been erased.",
    signOutFailed = "This device could not be unpaired. You are still signed in and can try again.",
    startCall = "Start Nqrb call", callablePeopleTitle = "People in your circle",
    callingDirectoryLoading = "Loading your saved contacts...",
    callingDirectoryEmpty = "Your list is empty. Add people from the People screen.",
    callingDirectoryError = "Saved contacts could not be loaded. Try again.",
    refreshCallingDirectory = "Refresh contacts",
    savedContactsTitle = "My circle", savedContactsBody = "A private list tied to your account. You choose who stays in it.",
    savedContactsLoading = "Loading saved contacts...", savedContactsEmpty = "You have not added any contacts yet.",
    savedContactsError = "Saved contacts could not be loaded. Try again.", loadMoreContacts = "Show more contacts",
    searchNqrbUsers = "Search Nqrb accounts", loadMoreSearchResults = "Show more results",
    searchPlaceholder = "Type at least two characters", addContact = "Add", removeContact = "Remove",
    contactSearchTooShort = "Type at least two characters to search.", contactSearchEmpty = "No matching accounts.",
    contactSearchError = "Search could not be completed. Try again.",
    inviteContactsTitle = "Share your account", inviteContactsBody = "One invite adds you both to each other's circle. Your friend can enter the code manually.",
    createInvite = "Create invite code", creatingInvite = "Creating invite code...", inviteCode = "Invite code",
    inviteShareLink = "Share link", copyInvite = "Copy invite", inviteCopied = "Copied.",
    shareInvite = "Share my account", copyInviteCode = "Copy code",
    shareInviteUnavailable = "Sharing isn't available here. Copy the code and send it instead.",
    inviteShareMessage = "Add me on Nqrb. Open People → Accept invite and enter this code: %s\nOpen in the app: %s",
    acceptInviteTitle = "Accept invitation", inviteCodePlaceholder = "Paste code or invite link",
    previewInvite = "Preview invitation", acceptInvite = "Accept and add both",
    invitePreviewBody = "%s will be added to your contacts, and you will appear in theirs.",
    inviteAccepted = "Invitation accepted and both contacts were added.", inviteInvalid = "This invite code is invalid or unavailable.",
    inviteExpired = "This invitation has expired.", inviteSelf = "You cannot accept your own invitation.",
    inviteClaimed = "This invitation has already been used.", inviteError = "Invitation could not be processed. Try again.",
    retry = "Try again",
    microphoneTitle = "Use your microphone for this call",
    microphoneBody = "NQRB needs microphone access to send your voice and to show the ongoing call on Android.",
    continueCall = "Continue call", browseDuringCall = "Browse the app during the call", returnToCall = "Return to call",
    cancel = "Cancel", connecting = "Connecting", ringing = "Waiting for answer",
    activeCall = "Call in progress", reconnecting = "Reconnecting", endingCall = "Ending call",
    callFailed = "Call could not start", mute = "Mute", unmute = "Unmute", speaker = "Speaker",
    earpiece = "Earpiece", audioRoute = "Audio route", endCall = "End call", answerCall = "Answer", declineCall = "Decline",
    microphoneDenied = "The call did not start because microphone access is unavailable. You can retry after enabling it.",
    onlineNow = "Online now", availableForCalls = "Available for calls", currentlyUnavailable = "Currently unavailable",
    historyLoading = "Loading call history...", historyEmpty = "No recorded calls yet.",
    historyError = "Call history could not be loaded. Try again.", loadMore = "Load older calls",
    allCalls = "All", addFromHistory = "Add to contacts", contactAdded = "Contact added.",
    contactAddUnavailable = "This caller cannot be added to NQRB contacts.",
    guestHistory = "Guest via link",
    incoming = "Incoming", outgoing = "Outgoing",
    completed = "Completed", rejected = "Rejected", missed = "Missed", cancelled = "Cancelled", expired = "Expired", failed = "Failed",
    callTime = "Call time", ringingDuration = "Ringing duration", connectedDuration = "Connected duration", dataUsage = "Data usage",
    currentPeriod = "Current period", from = "From", sent = "Sent", received = "Received", total = "Total",
    averagePerMinute = "per connected minute", resetUsage = "Start a new usage period",
    resetUsageConfirmation = "The counter will restart at zero. Historical call usage will not change.",
    confirmResetUsage = "Confirm new period",
    ringtoneTitle = "Incoming call ringtone", ringtoneBody = "Choose the sound you hear when someone calls you on Nqrb.",
    ringtoneMadar = "Madar · default", ringtoneGentle = "Gentle", ringtoneClassic = "Classic",
    ringtoneClear = "Clear · louder", ringtonePulse = "Pulse · louder",
    ringtoneDevice = "Phone ringtone", choosePhoneRingtone = "Choose a phone ringtone",
    previewRingtone = "Preview",
    guestCallLinkTitle = "Guest call link",
    guestCallLinkBody = "Create a temporary link for one person. The guest starts from the browser, and NQRB alerts you when they join even if you are not waiting on screen. The link expires soon, and the free direct connection may fail on some networks.",
    guestCallCreate = "Start guest call",
    guestCallStartWait = "Start and wait",
    guestCallWaitBody = "Stay on the call screen to answer quickly when the guest starts. If you leave, NQRB will still alert you when they join.",
    guestCallWaitingTitle = "Waiting for guest",
    guestCallWaitingInstruction = "Send the link and ask the guest to open it and start the call from their browser. The incoming call alert appears here when they join.",
    guestCallLinkReady = "Link ready to share with one guest",
    guestCallExpiresAt = "Link expires: %s",
    guestCallExpired = "This call link has expired. Create a new one before sharing.",
    guestCallCopyLink = "Copy link",
    guestCallShare = "Share link",
    guestCallShareUnavailable = "Sharing is unavailable. Copy the call link and send it yourself.",
    swipeToCallHint = "Swipe the card right to call, or tap the phone icon.",
    editContactNickname = "Private name", nicknameHint = "Only you will see this name",
    nicknameOriginal = "Nqrb account: %s", saveNickname = "Save name",
    nicknameError = "Could not save the name. Try again.",
    contactActions = "Contact actions",
    blockedTitle = "Blocked accounts", blockedBody = "Their calls and alerts will not reach you. You can unblock them any time.",
    blockContact = "Block account", unblockContact = "Unblock", blockConfirmTitle = "Block this account?",
    blockConfirmBody = "Their calls and alerts will stop, and they will see you as unavailable. The contact stays in your list until you remove it.",
    blockError = "Could not update blocked accounts. Check your connection and try again.", blockedLabel = "Blocked",
    blockedLoadError = "Blocked accounts could not be loaded. Try again.",
    clearSearch = "Clear search", showDetails = "Show details", hideDetails = "Hide details",
    notificationsTitle = "Call alerts", notificationsDisabledBody = "Nqrb notifications are off on this phone. Turn them on in phone settings to receive calls when the app is closed.",
    openNotificationSettings = "Open notification settings",
    appVersion = "App version",
)
