package com.botglobal.nqrb.app.ui

data class NqrbStrings(
    val productName: String, val productNameArabic: String,
    val heroEyebrow: String, val heroTitle: String, val heroBody: String,
    val foundationStatus: String, val foundationStatusBody: String,
    val primaryCallTitle: String, val primaryCallBody: String,
    val createCallLinkTitle: String, val createCallLinkBody: String,
    val home: String, val history: String, val people: String, val profile: String, val settings: String,
    val call: String, val openSettings: String, val back: String,
    val language: String, val appearance: String, val arabic: String, val english: String,
    val system: String, val light: String, val dark: String,
    val historyTitle: String, val historyBody: String, val peopleTitle: String, val peopleBody: String,
    val profileTitle: String, val profileBody: String, val selected: String,
    val signInTitle: String, val signInBody: String, val restoringTitle: String, val restoringBody: String,
    val continueWithGoogle: String,
    val googleConfigurationMissing: String, val googleUnavailable: String, val googleSignInFailed: String,
    val googleRejected: String, val accountLinkRequired: String, val networkFailure: String, val signInPrivacy: String,
    val contactsOnboardingTitle: String, val contactsOnboardingBody: String, val contactsStayLocal: String,
    val allowContacts: String, val notNow: String, val contactsEmpty: String, val contactsDenied: String,
    val contactsPermanentlyDenied: String, val refreshContacts: String, val logout: String,
    val startCall: String, val callablePeopleTitle: String, val callingDirectoryLoading: String,
    val callingDirectoryEmpty: String, val callingDirectoryError: String, val refreshCallingDirectory: String,
    val retry: String, val microphoneTitle: String, val microphoneBody: String,
    val continueCall: String, val cancel: String, val connecting: String, val ringing: String,
    val activeCall: String, val reconnecting: String, val endingCall: String, val callFailed: String,
    val mute: String, val unmute: String, val speaker: String, val earpiece: String, val audioRoute: String,
    val endCall: String,
    val answerCall: String, val declineCall: String, val microphoneDenied: String,
    val onlineNow: String, val availableForCalls: String, val currentlyUnavailable: String,
    val historyLoading: String, val historyEmpty: String, val historyError: String, val loadMore: String,
    val incoming: String, val outgoing: String, val completed: String, val rejected: String,
    val missed: String, val cancelled: String, val expired: String, val failed: String,
    val callTime: String, val ringingDuration: String, val connectedDuration: String, val dataUsage: String,
    val currentPeriod: String, val from: String, val sent: String, val received: String,
    val total: String, val averagePerMinute: String, val resetUsage: String,
    val resetUsageConfirmation: String, val confirmResetUsage: String,
)

fun nqrbStrings(languageTag: String): NqrbStrings = if (languageTag.startsWith("ar")) ArabicStrings else EnglishStrings

private val ArabicStrings = NqrbStrings(
    productName = "NQRB", productNameArabic = "نقرب", heroEyebrow = "صوت يجمعنا",
    heroTitle = "أقرب، أينما كنتم", heroBody = "تجربة اتصال صوتي صُممت لتكون واضحة، هادئة، وإنسانية.",
    foundationStatus = "اتصال آمن", foundationStatusBody = "الهوية والمكالمات وسجل نشاط الاتصال تعمل ضمن حسابك في نقرب.",
    primaryCallTitle = "اتصال مباشر", primaryCallBody = "مكان بسيط لاتصال صوتي بين شخصين.",
    createCallLinkTitle = "أنشئ رابط اتصال", createCallLinkBody = "شارك دعوة خاصة للانضمام لاحقًا من التطبيق أو المتصفح.",
    home = "الرئيسية", history = "السجل", people = "الأشخاص", profile = "حسابي", settings = "الإعدادات",
    call = "اتصال", openSettings = "فتح الإعدادات", back = "رجوع", language = "اللغة", appearance = "المظهر",
    arabic = "العربية", english = "English", system = "النظام", light = "فاتح", dark = "داكن",
    historyTitle = "سجل الاتصالات", historyBody = "راجع مكالماتك ومدة الاتصال واستخدام البيانات.",
    peopleTitle = "جهات الاتصال", peopleBody = "اسمح بالوصول الاختياري لعرض جهات اتصال جهازك محليًا.",
    profileTitle = "حسابك في نقرب", profileBody = "أنت مسجّل الدخول بجلسة منصة آمنة.", selected = "محدد",
    signInTitle = "خليك قريب.", signInBody = "سجّل دخولك وابدأ تجربتك على نقرب.",
    restoringTitle = "جارٍ استعادة جلستك", restoringBody = "لحظات ونكمل من حيث توقفت بأمان.",
    continueWithGoogle = "المتابعة باستخدام Google",
    googleConfigurationMissing = "تسجيل الدخول عبر Google غير مهيأ في هذا الإصدار. لم يتم تسجيل دخولك.",
    googleUnavailable = "تعذّر فتح اختيار حساب Google على هذا الجهاز.",
    googleSignInFailed = "تعذّر إكمال تسجيل الدخول. حاول مرة أخرى.",
    googleRejected = "لم يقبل الخادم بيانات تسجيل الدخول.",
    accountLinkRequired = "يوجد حساب بهذا البريد ويحتاج إلى ربط آمن قبل المتابعة.",
    networkFailure = "تعذّر الاتصال بالخادم. تحقق من الشبكة وحاول مرة أخرى.",
    signInPrivacy = "نستخدم بيانات Google لمرة واحدة لإثبات هويتك، ثم يحفظ نقرب جلسة المنصة الآمنة فقط.",
    contactsOnboardingTitle = "اعثر على الناس أسرع",
    contactsOnboardingBody = "اسمح لنقرب بالوصول إلى جهات الاتصال لتسهيل العثور على الأشخاص الذين تعرفهم.",
    contactsStayLocal = "جهات اتصالك تظل على جهازك في هذه المرحلة.",
    allowContacts = "السماح بجهات الاتصال", notNow = "ليس الآن", contactsEmpty = "لا توجد جهات اتصال لعرضها.",
    contactsDenied = "لم يتم السماح بالوصول. يمكنك المتابعة واختيار السماح لاحقًا.",
    contactsPermanentlyDenied = "الوصول متوقف. يمكنك تمكينه من إعدادات Android.",
    refreshContacts = "تحديث جهات الاتصال", logout = "تسجيل الخروج",
    startCall = "بدء مكالمة نقرب", callablePeopleTitle = "الأشخاص على نقرب",
    callingDirectoryLoading = "جاري تحميل المستخدمين المتاحين للاتصال في نقرب...",
    callingDirectoryEmpty = "لا يوجد مستخدمون متاحون للاتصال حاليًا.",
    callingDirectoryError = "تعذر تحميل المستخدمين. حاول مرة أخرى.",
    refreshCallingDirectory = "تحديث المستخدمين", retry = "حاول مرة أخرى",
    microphoneTitle = "استخدام الميكروفون أثناء المكالمة",
    microphoneBody = "يحتاج نقرب إلى الميكروفون لإرسال صوتك، وإلى إظهار حالة المكالمة الجارية على نظام Android.",
    continueCall = "متابعة المكالمة", cancel = "إلغاء", connecting = "جارٍ الاتصال", ringing = "في انتظار الرد",
    activeCall = "مكالمة جارية", reconnecting = "جارٍ استعادة الاتصال", endingCall = "جارٍ إنهاء المكالمة",
    callFailed = "تعذّر بدء المكالمة", mute = "كتم", unmute = "إلغاء الكتم", speaker = "مكبر الصوت",
    earpiece = "سماعة الهاتف", audioRoute = "مسار الصوت", endCall = "إنهاء المكالمة", answerCall = "رد", declineCall = "رفض",
    microphoneDenied = "لم يبدأ الاتصال لأن إذن الميكروفون غير متاح. يمكنك المحاولة مجددًا بعد تمكينه.",
    onlineNow = "متصل الآن", availableForCalls = "متاح للمكالمات", currentlyUnavailable = "غير متاح حاليًا",
    historyLoading = "جارٍ تحميل سجل الاتصالات...", historyEmpty = "لا توجد اتصالات مسجلة بعد.",
    historyError = "تعذر تحميل سجل الاتصالات. حاول مرة أخرى.", loadMore = "تحميل مكالمات أقدم", incoming = "واردة", outgoing = "صادرة",
    completed = "مكتملة", rejected = "مرفوضة", missed = "فائتة", cancelled = "ملغاة", expired = "انتهت المهلة", failed = "فشلت",
    callTime = "وقت الاتصال", ringingDuration = "مدة الرنين", connectedDuration = "مدة الاتصال", dataUsage = "استخدام البيانات",
    currentPeriod = "الفترة الحالية", from = "منذ", sent = "مرسل", received = "مستقبل", total = "الإجمالي",
    averagePerMinute = "لكل دقيقة اتصال", resetUsage = "بدء فترة استخدام جديدة",
    resetUsageConfirmation = "سيبدأ العداد من الصفر، ولن يتغير استخدام المكالمات السابقة.",
    confirmResetUsage = "تأكيد بدء فترة جديدة",
)

private val EnglishStrings = NqrbStrings(
    productName = "NQRB", productNameArabic = "نقرب", heroEyebrow = "VOICE THAT BRINGS US CLOSER",
    heroTitle = "Closer, wherever you are", heroBody = "A voice experience designed to feel clear, calm, and human.",
    foundationStatus = "Secure calling", foundationStatusBody = "Identity, calls, and communication activity stay scoped to your NQRB account.",
    primaryCallTitle = "Direct call", primaryCallBody = "A focused place for a premium one-to-one voice conversation.",
    createCallLinkTitle = "Create a call link", createCallLinkBody = "Share a private invitation to join later from the app or browser.",
    home = "Home", history = "History", people = "People", profile = "Profile", settings = "Settings", call = "Call",
    openSettings = "Open settings", back = "Back", language = "Language", appearance = "Appearance",
    arabic = "العربية", english = "English", system = "System", light = "Light", dark = "Dark",
    historyTitle = "Call history", historyBody = "Review your calls, connected time, and media data usage.",
    peopleTitle = "Device contacts", peopleBody = "Allow optional access to view your device contacts locally.",
    profileTitle = "Your NQRB profile", profileBody = "You are signed in with a secure platform session.", selected = "Selected",
    signInTitle = "Stay close.", signInBody = "Sign in and get started with NQRB.",
    restoringTitle = "Restoring your session", restoringBody = "One moment while NQRB securely picks up where you left off.",
    continueWithGoogle = "Continue with Google",
    googleConfigurationMissing = "Google sign-in is not configured in this build. You have not been signed in.",
    googleUnavailable = "Google account selection is unavailable on this device.",
    googleSignInFailed = "Sign-in could not be completed. Please try again.",
    googleRejected = "The server did not accept this sign-in credential.",
    accountLinkRequired = "An account with this email exists and requires secure linking before you can continue.",
    networkFailure = "The server could not be reached. Check your connection and try again.",
    signInPrivacy = "Google data is used once to prove your identity; NQRB then stores only the secure platform session.",
    contactsOnboardingTitle = "Find people faster",
    contactsOnboardingBody = "Allow NQRB to access your contacts so you can find people you know more easily.",
    contactsStayLocal = "Your contacts stay on your device at this stage.",
    allowContacts = "Allow contacts", notNow = "Not now", contactsEmpty = "There are no contacts to show.",
    contactsDenied = "Access was not allowed. You can continue and choose to allow it later.",
    contactsPermanentlyDenied = "Access is disabled. You can enable it from Android settings.",
    refreshContacts = "Refresh contacts", logout = "Sign out",
    startCall = "Start NQRB call", callablePeopleTitle = "People on NQRB",
    callingDirectoryLoading = "Loading people available to call on NQRB...",
    callingDirectoryEmpty = "No users are currently available to call.",
    callingDirectoryError = "People could not be loaded. Please try again.",
    refreshCallingDirectory = "Refresh people", retry = "Try again",
    microphoneTitle = "Use your microphone for this call",
    microphoneBody = "NQRB needs microphone access to send your voice and to show the ongoing call on Android.",
    continueCall = "Continue call", cancel = "Cancel", connecting = "Connecting", ringing = "Waiting for answer",
    activeCall = "Call in progress", reconnecting = "Reconnecting", endingCall = "Ending call",
    callFailed = "Call could not start", mute = "Mute", unmute = "Unmute", speaker = "Speaker",
    earpiece = "Earpiece", audioRoute = "Audio route", endCall = "End call", answerCall = "Answer", declineCall = "Decline",
    microphoneDenied = "The call did not start because microphone access is unavailable. You can retry after enabling it.",
    onlineNow = "Online now", availableForCalls = "Available for calls", currentlyUnavailable = "Currently unavailable",
    historyLoading = "Loading call history...", historyEmpty = "No recorded calls yet.",
    historyError = "Call history could not be loaded. Try again.", loadMore = "Load older calls", incoming = "Incoming", outgoing = "Outgoing",
    completed = "Completed", rejected = "Rejected", missed = "Missed", cancelled = "Cancelled", expired = "Expired", failed = "Failed",
    callTime = "Call time", ringingDuration = "Ringing duration", connectedDuration = "Connected duration", dataUsage = "Data usage",
    currentPeriod = "Current period", from = "From", sent = "Sent", received = "Received", total = "Total",
    averagePerMinute = "per connected minute", resetUsage = "Start a new usage period",
    resetUsageConfirmation = "The counter will restart at zero. Historical call usage will not change.",
    confirmResetUsage = "Confirm new period",
)
