package com.botglobal.familygames.app.ui

import com.botglobal.familygames.app.state.AppLanguage

data class FamilyGamesStrings(
    val appName: String,
    val tagline: String,
    val continueGuest: String,
    val signIn: String,
    val createAccount: String,
    val displayName: String,
    val userNameOrEmail: String,
    val userName: String,
    val email: String,
    val password: String,
    val back: String,
    val welcome: String,
    val catalogTitle: String,
    val catalogSubtitle: String,
    val xoTitle: String,
    val xoSubtitle: String,
    val play: String,
    val classicRules: String,
    val classicDescription: String,
    val extendedRules: String,
    val extendedDescription: String,
    val included: String,
    val locked: String,
    val continueLabel: String,
    val createGame: String,
    val joinGame: String,
    val joinCode: String,
    val joinCodeHint: String,
    val lobby: String,
    val shareCode: String,
    val invitePlayer: String,
    val invitationTitle: String,
    val invitationSubtitle: String,
    val invitationQrDescription: String,
    val shareInvitation: String,
    val scanQr: String,
    val inviteExpiresSoon: String,
    val cameraTitle: String,
    val cameraReason: String,
    val scanInvitationPrompt: String,
    val continueCamera: String,
    val cancel: String,
    val close: String,
    val waitingOpponent: String,
    val ready: String,
    val readyWaiting: String,
    val you: String,
    val opponent: String,
    val yourTurn: String,
    val opponentTurn: String,
    val connecting: String,
    val connected: String,
    val reconnecting: String,
    val disconnected: String,
    val recovered: String,
    val actionUnavailableOffline: String,
    val opponentDisconnected: String,
    val retry: String,
    val voiceUnavailable: String,
    val winner: String,
    val youWon: String,
    val opponentWon: String,
    val draw: String,
    val rematch: String,
    val acceptRematch: String,
    val rematchWaiting: String,
    val exit: String,
    val loading: String,
    val genericError: String,
    val sessionNotFound: String,
    val wrongTurn: String,
    val occupiedCell: String,
    val staleState: String,
    val recoveryFailed: String,
    val entitlementRequired: String,
    val invitationInvalid: String,
    val invitationExpired: String,
    val invitationInactive: String,
    val invitationWrongApplication: String,
    val sessionNotJoinable: String,
    val cameraPermissionDenied: String,
    val qrScannerUnavailable: String,
    val shareUnavailable: String,
    val logout: String,
    val language: String,
    val boardCellEmpty: String,
    val boardCellMarked: (String) -> String,
    val updateAvailable: String,
    val updateRequired: String,
    val updateNow: String,
    val updateLater: String,
    val optionalUpdateMessage: String,
    val requiredUpdateMessage: String,
)

fun strings(language: AppLanguage): FamilyGamesStrings =
    if (language == AppLanguage.Arabic) ArabicStrings else EnglishStrings

private val ArabicStrings = FamilyGamesStrings(
    appName = "لَمّة",
    tagline = "اللعب أحلى لما يجمعنا",
    continueGuest = "الدخول كضيف",
    signIn = "تسجيل الدخول",
    createAccount = "إنشاء حساب",
    displayName = "اسمك داخل اللعبة",
    userNameOrEmail = "اسم المستخدم أو البريد",
    userName = "اسم المستخدم",
    email = "البريد الإلكتروني",
    password = "كلمة المرور",
    back = "رجوع",
    welcome = "أهلًا",
    catalogTitle = "اختار لعبتك",
    catalogSubtitle = "أول تحدّي جاهز.. والباقي جاي في الطريق",
    xoTitle = "إكس أو",
    xoSubtitle = "مواجهة مباشرة بين لاعبين",
    play = "العب الآن",
    classicRules = "الكلاسيكي ٣ × ٣",
    classicDescription = "ثلاث علامات على خط واحد للفوز",
    extendedRules = "التحدّي ٥ × ٥",
    extendedDescription = "أربع علامات للفوز — قريبًا",
    included = "مجاني",
    locked = "غير متاح حاليًا",
    continueLabel = "متابعة",
    createGame = "إنشاء لعبة جديدة",
    joinGame = "الانضمام بلعبة",
    joinCode = "كود اللعبة",
    joinCodeHint = "مثال: AX7K2Q",
    lobby = "غرفة الانتظار",
    shareCode = "شارك الكود مع اللاعب الثاني",
    invitePlayer = "دعوة لاعب",
    invitationTitle = "ادعُ لاعبًا",
    invitationSubtitle = "خلي اللاعب يمسح الرمز أو ابعت له الدعوة",
    invitationQrDescription = "رمز دعوة الانضمام للعبة",
    shareInvitation = "مشاركة الدعوة",
    scanQr = "مسح رمز دعوة",
    inviteExpiresSoon = "الدعوة آمنة وتنتهي صلاحيتها بعد وقت قصير",
    cameraTitle = "مسح رمز الدعوة",
    cameraReason = "نحتاج الكاميرا فقط لمسح رمز دعوة لَمّة. لن تُفتح إلا بعد موافقتك.",
    scanInvitationPrompt = "وجّه الكاميرا نحو رمز الدعوة",
    continueCamera = "متابعة للكاميرا",
    cancel = "إلغاء",
    close = "إغلاق",
    waitingOpponent = "في انتظار اللاعب الثاني",
    ready = "أنا جاهز",
    readyWaiting = "جاهز — ننتظر المنافس",
    you = "أنت",
    opponent = "المنافس",
    yourTurn = "دورك الآن",
    opponentTurn = "دور المنافس",
    connecting = "جاري الاتصال",
    connected = "متصل",
    reconnecting = "نعيد الاتصال…",
    disconnected = "الاتصال متوقف",
    recovered = "تم استرجاع اللعبة",
    actionUnavailableOffline = "اللعب متوقف مؤقتًا لحد ما الاتصال يرجع",
    opponentDisconnected = "انقطع اتصال اللاعب الآخر، جاري انتظار عودته",
    retry = "إعادة المحاولة",
    voiceUnavailable = "الصوت غير متاح في هذا الوضع",
    winner = "الفائز",
    youWon = "أحسنت! كسبت الجولة",
    opponentWon = "المنافس كسب الجولة",
    draw = "تعادل جميل!",
    rematch = "طلب جولة جديدة",
    acceptRematch = "قبول الجولة الجديدة",
    rematchWaiting = "تم إرسال الطلب",
    exit = "الخروج للرئيسية",
    loading = "لحظة واحدة…",
    genericError = "حصلت مشكلة. جرّب مرة ثانية.",
    sessionNotFound = "لم نجد اللعبة بهذا الكود.",
    wrongTurn = "استنى دورك.",
    occupiedCell = "المربع مستخدم بالفعل.",
    staleState = "تم تحديث اللعبة. جرّب حركتك من جديد.",
    recoveryFailed = "تعذر استرجاع اللعبة. تأكد من الاتصال وحاول مرة ثانية.",
    entitlementRequired = "هذا الوضع غير متاح في حسابك حاليًا.",
    invitationInvalid = "رمز الدعوة غير صحيح.",
    invitationExpired = "انتهت صلاحية الدعوة. اطلب دعوة جديدة من صاحب اللعبة.",
    invitationInactive = "الدعوة لم تعد متاحة.",
    invitationWrongApplication = "هذه الدعوة لا تخص تطبيق لَمّة.",
    sessionNotJoinable = "اللعبة لم تعد متاحة للانضمام.",
    cameraPermissionDenied = "يلزم السماح بالكاميرا لمسح رمز الدعوة.",
    qrScannerUnavailable = "ماسح الرموز غير متاح على هذا الجهاز.",
    shareUnavailable = "المشاركة غير متاحة حاليًا.",
    logout = "تسجيل الخروج",
    language = "English",
    boardCellEmpty = "مربع فارغ",
    boardCellMarked = { mark -> "مربع بعلامة $mark" },
    updateAvailable = "تحديث جديد متاح",
    updateRequired = "التحديث مطلوب",
    updateNow = "تحديث الآن",
    updateLater = "لاحقًا",
    optionalUpdateMessage = "نزّل أحدث إصدار لأفضل تجربة لعب.",
    requiredUpdateMessage = "لازم تحدّث التطبيق قبل ما تكمل اللعب.",
)

private val EnglishStrings = FamilyGamesStrings(
    appName = "Lamma",
    tagline = "Play is better together",
    continueGuest = "Continue as Guest",
    signIn = "Sign In",
    createAccount = "Create Account",
    displayName = "Your game name",
    userNameOrEmail = "Username or email",
    userName = "Username",
    email = "Email",
    password = "Password",
    back = "Back",
    welcome = "Welcome",
    catalogTitle = "Choose your game",
    catalogSubtitle = "The first challenge is ready, with more on the way",
    xoTitle = "Tic-Tac-Toe",
    xoSubtitle = "A live head-to-head match",
    play = "Play now",
    classicRules = "Classic 3 × 3",
    classicDescription = "Connect three marks to win",
    extendedRules = "Challenge 5 × 5",
    extendedDescription = "Connect four — coming soon",
    included = "Free",
    locked = "Currently unavailable",
    continueLabel = "Continue",
    createGame = "Create new game",
    joinGame = "Join a game",
    joinCode = "Game code",
    joinCodeHint = "Example: AX7K2Q",
    lobby = "Game lobby",
    shareCode = "Share this code with player two",
    invitePlayer = "Invite a player",
    invitationTitle = "Invite a player",
    invitationSubtitle = "Let them scan the code or send the invitation",
    invitationQrDescription = "Game join invitation QR code",
    shareInvitation = "Share invitation",
    scanQr = "Scan invitation QR",
    inviteExpiresSoon = "This secure invitation expires shortly",
    cameraTitle = "Scan an invitation",
    cameraReason = "Camera access is used only to scan a Lamma invitation QR. It opens after you continue.",
    scanInvitationPrompt = "Point the camera at the invitation QR",
    continueCamera = "Continue to camera",
    cancel = "Cancel",
    close = "Close",
    waitingOpponent = "Waiting for player two",
    ready = "I'm ready",
    readyWaiting = "Ready — waiting for opponent",
    you = "You",
    opponent = "Opponent",
    yourTurn = "Your turn",
    opponentTurn = "Opponent's turn",
    connecting = "Connecting",
    connected = "Connected",
    reconnecting = "Reconnecting…",
    disconnected = "Offline",
    recovered = "Game recovered",
    actionUnavailableOffline = "Moves are paused until the connection recovers",
    opponentDisconnected = "Opponent disconnected. Waiting for them to reconnect.",
    retry = "Try again",
    voiceUnavailable = "Voice is unavailable in this mode",
    winner = "Winner",
    youWon = "Great game — you won!",
    opponentWon = "Your opponent won this round",
    draw = "A fine draw!",
    rematch = "Request rematch",
    acceptRematch = "Accept rematch",
    rematchWaiting = "Request sent",
    exit = "Exit to home",
    loading = "One moment…",
    genericError = "Something went wrong. Please try again.",
    sessionNotFound = "No game was found with that code.",
    wrongTurn = "Wait for your turn.",
    occupiedCell = "That cell is already occupied.",
    staleState = "The game changed. Try your move again.",
    recoveryFailed = "The game could not be recovered. Check your connection and try again.",
    entitlementRequired = "This mode is not available for your membership.",
    invitationInvalid = "That invitation code is invalid.",
    invitationExpired = "This invitation expired. Ask the host for a new one.",
    invitationInactive = "This invitation is no longer available.",
    invitationWrongApplication = "This invitation is not for Lamma.",
    sessionNotJoinable = "This game is no longer open to new players.",
    cameraPermissionDenied = "Camera permission is needed to scan an invitation.",
    qrScannerUnavailable = "QR scanning is unavailable on this device.",
    shareUnavailable = "Sharing is currently unavailable.",
    logout = "Sign out",
    language = "العربية",
    boardCellEmpty = "Empty cell",
    boardCellMarked = { mark -> "Cell marked $mark" },
    updateAvailable = "An update is available",
    updateRequired = "Update required",
    updateNow = "Update now",
    updateLater = "Later",
    optionalUpdateMessage = "Install the latest version for the best game experience.",
    requiredUpdateMessage = "Update the app before continuing.",
)

fun FamilyGamesStrings.error(code: String?): String = when (code) {
    null -> ""
    "session_not_found", "active_session_not_found" -> sessionNotFound
    "wrong_player" -> wrongTurn
    "occupied_cell" -> occupiedCell
    "stale_version", "duplicate_command", "concurrent_move", "duplicate_or_concurrent_move", "game_completed" -> staleState
    "recovery_failed" -> recoveryFailed
    "entitlement_required" -> entitlementRequired
    "invitation_invalid" -> invitationInvalid
    "invitation_expired" -> invitationExpired
    "invitation_inactive", "already_participant" -> invitationInactive
    "invitation_wrong_application" -> invitationWrongApplication
    "session_not_joinable" -> sessionNotJoinable
    "camera_permission_denied" -> cameraPermissionDenied
    "qr_scanner_unavailable" -> qrScannerUnavailable
    "share_unavailable" -> shareUnavailable
    else -> genericError
}
