package com.botglobal.familygames.app.ui

import com.botglobal.familygames.app.state.AppLanguage

data class FamilyGamesStrings(
    val appName: String,
    val tagline: String,
    val continueGuest: String,
    val signIn: String,
    val createAccount: String,
    val displayName: String,
    val userNameOrEmail: String,
    val userName: String,
    val email: String,
    val password: String,
    val back: String,
    val welcome: String,
    val catalogTitle: String,
    val catalogSubtitle: String,
    val xoTitle: String,
    val xoSubtitle: String,
    val play: String,
    val classicRules: String,
    val classicDescription: String,
    val extendedRules: String,
    val extendedDescription: String,
    val included: String,
    val locked: String,
    val continueLabel: String,
    val createGame: String,
    val joinGame: String,
    val joinCode: String,
    val joinCodeHint: String,
    val lobby: String,
    val shareCode: String,
    val waitingOpponent: String,
    val ready: String,
    val readyWaiting: String,
    val you: String,
    val opponent: String,
    val yourTurn: String,
    val opponentTurn: String,
    val connecting: String,
    val connected: String,
    val reconnecting: String,
    val disconnected: String,
    val retry: String,
    val voiceUnavailable: String,
    val winner: String,
    val youWon: String,
    val opponentWon: String,
    val draw: String,
    val rematch: String,
    val acceptRematch: String,
    val rematchWaiting: String,
    val exit: String,
    val loading: String,
    val genericError: String,
    val sessionNotFound: String,
    val wrongTurn: String,
    val occupiedCell: String,
    val staleState: String,
    val entitlementRequired: String,
    val logout: String,
    val language: String,
    val boardCellEmpty: String,
    val boardCellMarked: (String) -> String,
    val updateAvailable: String,
    val updateRequired: String,
    val updateNow: String,
    val updateLater: String,
    val optionalUpdateMessage: String,
    val requiredUpdateMessage: String,
)

fun strings(language: AppLanguage): FamilyGamesStrings =
    if (language == AppLanguage.Arabic) ArabicStrings else EnglishStrings

private val ArabicStrings = FamilyGamesStrings(
    appName = "ألعاب العائلة",
    tagline = "اللعب أحلى لما يجمعنا",
    continueGuest = "الدخول كضيف",
    signIn = "تسجيل الدخول",
    createAccount = "إنشاء حساب",
    displayName = "اسمك داخل اللعبة",
    userNameOrEmail = "اسم المستخدم أو البريد",
    userName = "اسم المستخدم",
    email = "البريد الإلكتروني",
    password = "كلمة المرور",
    back = "رجوع",
    welcome = "أهلًا",
    catalogTitle = "اختار لعبتك",
    catalogSubtitle = "أول تحدّي جاهز.. والباقي جاي في الطريق",
    xoTitle = "إكس أو",
    xoSubtitle = "مواجهة مباشرة بين لاعبين",
    play = "العب الآن",
    classicRules = "الكلاسيكي ٣ × ٣",
    classicDescription = "ثلاث علامات على خط واحد للفوز",
    extendedRules = "التحدّي ٥ × ٥",
    extendedDescription = "أربع علامات للفوز — قريبًا",
    included = "مجاني",
    locked = "غير متاح حاليًا",
    continueLabel = "متابعة",
    createGame = "إنشاء لعبة جديدة",
    joinGame = "الانضمام بلعبة",
    joinCode = "كود اللعبة",
    joinCodeHint = "مثال: AX7K2Q",
    lobby = "غرفة الانتظار",
    shareCode = "شارك الكود مع اللاعب الثاني",
    waitingOpponent = "في انتظار اللاعب الثاني",
    ready = "أنا جاهز",
    readyWaiting = "جاهز — ننتظر المنافس",
    you = "أنت",
    opponent = "المنافس",
    yourTurn = "دورك الآن",
    opponentTurn = "دور المنافس",
    connecting = "جاري الاتصال",
    connected = "متصل",
    reconnecting = "نعيد الاتصال…",
    disconnected = "الاتصال متوقف",
    retry = "إعادة المحاولة",
    voiceUnavailable = "الصوت غير متاح في هذا الوضع",
    winner = "الفائز",
    youWon = "أحسنت! كسبت الجولة",
    opponentWon = "المنافس كسب الجولة",
    draw = "تعادل جميل!",
    rematch = "طلب جولة جديدة",
    acceptRematch = "قبول الجولة الجديدة",
    rematchWaiting = "تم إرسال الطلب",
    exit = "الخروج للرئيسية",
    loading = "لحظة واحدة…",
    genericError = "حصلت مشكلة. جرّب مرة ثانية.",
    sessionNotFound = "لم نجد اللعبة بهذا الكود.",
    wrongTurn = "استنى دورك.",
    occupiedCell = "المربع مستخدم بالفعل.",
    staleState = "تم تحديث اللعبة. جرّب حركتك من جديد.",
    entitlementRequired = "هذا الوضع غير متاح في حسابك حاليًا.",
    logout = "تسجيل الخروج",
    language = "English",
    boardCellEmpty = "مربع فارغ",
    boardCellMarked = { mark -> "مربع بعلامة $mark" },
    updateAvailable = "تحديث جديد متاح",
    updateRequired = "التحديث مطلوب",
    updateNow = "تحديث الآن",
    updateLater = "لاحقًا",
    optionalUpdateMessage = "نزّل أحدث إصدار لأفضل تجربة لعب.",
    requiredUpdateMessage = "لازم تحدّث التطبيق قبل ما تكمل اللعب.",
)

private val EnglishStrings = FamilyGamesStrings(
    appName = "Family Games",
    tagline = "Play is better together",
    continueGuest = "Continue as Guest",
    signIn = "Sign In",
    createAccount = "Create Account",
    displayName = "Your game name",
    userNameOrEmail = "Username or email",
    userName = "Username",
    email = "Email",
    password = "Password",
    back = "Back",
    welcome = "Welcome",
    catalogTitle = "Choose your game",
    catalogSubtitle = "The first challenge is ready, with more on the way",
    xoTitle = "Tic-Tac-Toe",
    xoSubtitle = "A live head-to-head match",
    play = "Play now",
    classicRules = "Classic 3 × 3",
    classicDescription = "Connect three marks to win",
    extendedRules = "Challenge 5 × 5",
    extendedDescription = "Connect four — coming soon",
    included = "Free",
    locked = "Currently unavailable",
    continueLabel = "Continue",
    createGame = "Create new game",
    joinGame = "Join a game",
    joinCode = "Game code",
    joinCodeHint = "Example: AX7K2Q",
    lobby = "Game lobby",
    shareCode = "Share this code with player two",
    waitingOpponent = "Waiting for player two",
    ready = "I'm ready",
    readyWaiting = "Ready — waiting for opponent",
    you = "You",
    opponent = "Opponent",
    yourTurn = "Your turn",
    opponentTurn = "Opponent's turn",
    connecting = "Connecting",
    connected = "Connected",
    reconnecting = "Reconnecting…",
    disconnected = "Offline",
    retry = "Try again",
    voiceUnavailable = "Voice is unavailable in this mode",
    winner = "Winner",
    youWon = "Great game — you won!",
    opponentWon = "Your opponent won this round",
    draw = "A fine draw!",
    rematch = "Request rematch",
    acceptRematch = "Accept rematch",
    rematchWaiting = "Request sent",
    exit = "Exit to home",
    loading = "One moment…",
    genericError = "Something went wrong. Please try again.",
    sessionNotFound = "No game was found with that code.",
    wrongTurn = "Wait for your turn.",
    occupiedCell = "That cell is already occupied.",
    staleState = "The game changed. Try your move again.",
    entitlementRequired = "This mode is not available for your membership.",
    logout = "Sign out",
    language = "العربية",
    boardCellEmpty = "Empty cell",
    boardCellMarked = { mark -> "Cell marked $mark" },
    updateAvailable = "An update is available",
    updateRequired = "Update required",
    updateNow = "Update now",
    updateLater = "Later",
    optionalUpdateMessage = "Install the latest version for the best game experience.",
    requiredUpdateMessage = "Update the app before continuing.",
)

fun FamilyGamesStrings.error(code: String?): String = when (code) {
    null -> ""
    "session_not_found", "active_session_not_found" -> sessionNotFound
    "wrong_player" -> wrongTurn
    "occupied_cell" -> occupiedCell
    "stale_version", "concurrent_move", "duplicate_or_concurrent_move" -> staleState
    "entitlement_required" -> entitlementRequired
    else -> genericError
}
