// <auto-generated />
using System;
using BotGlobal.Communication.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BotGlobal.Communication.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(CommunicationDbContext))]
    partial class CommunicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("communication")
                .HasAnnotation("ProductVersion", "10.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("BotGlobal.Communication.Domain.Calls.CallSession", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset?>("AnsweredAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("CalleeUserId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("CallerUserId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("ClientCallId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<Guid?>("ConversationId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("EndReason")
                        .HasMaxLength(24)
                        .IsUnicode(false)
                        .HasColumnType("varchar(24)");

                    b.Property<DateTimeOffset?>("EndedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasMaxLength(16)
                        .IsUnicode(false)
                        .HasColumnType("varchar(16)");

                    b.Property<DateTimeOffset>("StartedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(16)
                        .IsUnicode(false)
                        .HasColumnType("varchar(16)");

                    b.HasKey("Id");

                    b.HasIndex("CalleeUserId", "StartedAtUtc")
                        .HasDatabaseName("IX_CallSessions_Callee_StartedAtUtc");

                    b.HasIndex("CallerUserId", "ClientCallId")
                        .IsUnique()
                        .HasDatabaseName("UX_CallSessions_Caller_ClientCallId");

                    b.HasIndex("ConversationId", "StartedAtUtc")
                        .HasDatabaseName("IX_CallSessions_Conversation_StartedAtUtc");

                    b.ToTable("CallSessions", "communication", t =>
                        {
                            t.HasCheckConstraint("CK_CallSessions_DifferentUsers", "[CallerUserId] <> [CalleeUserId]");

                            t.HasCheckConstraint("CK_CallSessions_EndReason", "[EndReason] IS NULL OR [EndReason] IN ('Ended','Rejected','Cancelled','Busy','CallsDisabled','Failed')");

                            t.HasCheckConstraint("CK_CallSessions_Kind", "[Kind] IN ('Voice','Video')");

                            t.HasCheckConstraint("CK_CallSessions_Status", "[Status] IN ('Ringing','Active','Ended')");

                            t.HasCheckConstraint("CK_CallSessions_TimeOrder", "([AnsweredAtUtc] IS NULL OR [AnsweredAtUtc] >= [StartedAtUtc]) AND ([EndedAtUtc] IS NULL OR [EndedAtUtc] >= [StartedAtUtc]) AND ([AnsweredAtUtc] IS NULL OR [EndedAtUtc] IS NULL OR [EndedAtUtc] >= [AnsweredAtUtc])");
                        });
                });

            modelBuilder.Entity("BotGlobal.Communication.Domain.Conversations.Conversation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("CreatedByUserId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("DirectKey")
                        .HasMaxLength(257)
                        .IsUnicode(false)
                        .HasColumnType("varchar(257)");

                    b.Property<DateTimeOffset>("LastActivityAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Title")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(16)
                        .IsUnicode(false)
                        .HasColumnType("varchar(16)");

                    b.HasKey("Id");

                    b.HasIndex("DirectKey")
                        .IsUnique()
                        .HasDatabaseName("UX_Conversations_DirectKey")
                        .HasFilter("[DirectKey] IS NOT NULL");

                    b.HasIndex("LastActivityAtUtc")
                        .HasDatabaseName("IX_Conversations_LastActivityAtUtc");

                    b.ToTable("Conversations", "communication", t =>
                        {
                            t.HasCheckConstraint("CK_Conversations_ActivityTime", "[LastActivityAtUtc] >= [CreatedAtUtc]");

                            t.HasCheckConstraint("CK_Conversations_Shape", "([Type] = 'Direct' AND [DirectKey] IS NOT NULL AND [Title] IS NULL) OR ([Type] = 'Group' AND [DirectKey] IS NULL AND [Title] IS NOT NULL)");

                            t.HasCheckConstraint("CK_Conversations_Type", "[Type] IN ('Direct','Group')");
                        });
                });

            modelBuilder.Entity("BotGlobal.Communication.Domain.Conversations.ConversationParticipant", b =>
                {
                    b.Property<Guid>("ConversationId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("UserId")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<DateTimeOffset>("JoinedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset?>("LeftAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(16)
                        .IsUnicode(false)
                        .HasColumnType("varchar(16)");

                    b.HasKey("ConversationId", "UserId");

                    b.HasIndex("UserId")
                        .HasDatabaseName("IX_ConversationParticipants_ActiveUser")
                        .HasFilter("[LeftAtUtc] IS NULL");

                    b.ToTable("ConversationParticipants", "communication", t =>
                        {
                            t.HasCheckConstraint("CK_ConversationParticipants_MembershipTime", "[LeftAtUtc] IS NULL OR [LeftAtUtc] >= [JoinedAtUtc]");

                            t.HasCheckConstraint("CK_ConversationParticipants_Role", "[Role] IN ('Member','Admin','Owner')");
                        });
                });

            modelBuilder.Entity("BotGlobal.Communication.Domain.Messaging.Message", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ClientMessageId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<Guid>("ConversationId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasMaxLength(16)
                        .IsUnicode(false)
                        .HasColumnType("varchar(16)");

                    b.Property<string>("SenderUserId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<long>("SequenceNumber")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("SequenceNumber"));

                    b.Property<string>("TextContent")
                        .HasMaxLength(4000)
                        .HasColumnType("nvarchar(4000)");

                    b.Property<string>("Url")
                        .HasMaxLength(2048)
                        .HasColumnType("nvarchar(2048)");

                    b.HasKey("Id");

                    b.HasIndex("ConversationId", "CreatedAtUtc")
                        .HasDatabaseName("IX_Messages_Conversation_CreatedAtUtc");

                    b.HasIndex("ConversationId", "SequenceNumber")
                        .IsUnique()
                        .HasDatabaseName("UX_Messages_Conversation_Sequence");

                    b.HasIndex("SenderUserId", "ClientMessageId")
                        .IsUnique()
                        .HasDatabaseName("UX_Messages_Sender_ClientMessageId");

                    b.ToTable("Messages", "communication", t =>
                        {
                            t.HasCheckConstraint("CK_Messages_Content", "([Kind] = 'Text' AND [TextContent] IS NOT NULL AND [Url] IS NULL) OR ([Kind] = 'Link' AND [Url] IS NOT NULL) OR ([Kind] IN ('Image','Video','Voice','File'))");

                            t.HasCheckConstraint("CK_Messages_Kind", "[Kind] IN ('Text','Link','Image','Video','Voice','File')");
                        });
                });

            modelBuilder.Entity("BotGlobal.Communication.Domain.Messaging.MessageReceipt", b =>
                {
                    b.Property<Guid>("MessageId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("UserId")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<DateTimeOffset?>("DeliveredAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset?>("ReadAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.HasKey("MessageId", "UserId");

                    b.HasIndex("UserId", "ReadAtUtc")
                        .HasDatabaseName("IX_MessageReceipts_User_ReadAtUtc");

                    b.ToTable("MessageReceipts", "communication", t =>
                        {
                            t.HasCheckConstraint("CK_MessageReceipts_ReadRequiresDelivery", "[ReadAtUtc] IS NULL OR [DeliveredAtUtc] IS NOT NULL");

                            t.HasCheckConstraint("CK_MessageReceipts_TimeOrder", "[ReadAtUtc] IS NULL OR [ReadAtUtc] >= [DeliveredAtUtc]");
                        });
                });

            modelBuilder.Entity("BotGlobal.Communication.Domain.Preferences.UserCommunicationPreference", b =>
                {
                    b.Property<string>("UserId")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<bool>("AllowVideoCalls")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<bool>("AllowVoiceCalls")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<DateTimeOffset>("UpdatedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.HasKey("UserId");

                    b.ToTable("UserCommunicationPreferences", "communication");
                });

            modelBuilder.Entity("BotGlobal.Communication.Domain.Calls.CallSession", b =>
                {
                    b.HasOne("BotGlobal.Communication.Domain.Conversations.Conversation", null)
                        .WithMany()
                        .HasForeignKey("ConversationId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("BotGlobal.Communication.Domain.Conversations.ConversationParticipant", b =>
                {
                    b.HasOne("BotGlobal.Communication.Domain.Conversations.Conversation", null)
                        .WithMany("Participants")
                        .HasForeignKey("ConversationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("BotGlobal.Communication.Domain.Messaging.Message", b =>
                {
                    b.HasOne("BotGlobal.Communication.Domain.Conversations.Conversation", null)
                        .WithMany()
                        .HasForeignKey("ConversationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("BotGlobal.Communication.Domain.Messaging.MessageReceipt", b =>
                {
                    b.HasOne("BotGlobal.Communication.Domain.Messaging.Message", null)
                        .WithMany("Receipts")
                        .HasForeignKey("MessageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("BotGlobal.Communication.Domain.Conversations.Conversation", b =>
                {
                    b.Navigation("Participants");
                });

            modelBuilder.Entity("BotGlobal.Communication.Domain.Messaging.Message", b =>
                {
                    b.Navigation("Receipts");
                });
#pragma warning restore 612, 618
        }
    }
}
