package com.enpo.connect.app.ui

data class EnpoStrings(
    val productName: String,
    val organizationName: String,
    val foundationEyebrow: String,
    val foundationTitle: String,
    val foundationBody: String,
    val sliceNotice: String,
    val settings: String,
    val language: String,
    val appearance: String,
    val about: String,
    val arabic: String,
    val english: String,
    val system: String,
    val light: String,
    val dark: String,
    val back: String,
    val version: String,
    val platformFoundation: String,
    val platformFoundationBody: String,
    val deferredCapabilities: String,
    val deferredCapabilitiesBody: String,
) {
    fun allValues(): List<String> = listOf(
        productName,
        organizationName,
        foundationEyebrow,
        foundationTitle,
        foundationBody,
        sliceNotice,
        settings,
        language,
        appearance,
        about,
        arabic,
        english,
        system,
        light,
        dark,
        back,
        version,
        platformFoundation,
        platformFoundationBody,
        deferredCapabilities,
        deferredCapabilitiesBody,
    )
}

fun enpoStrings(languageTag: String): EnpoStrings =
    if (languageTag.startsWith("ar")) ArabicStrings else EnglishStrings

private val ArabicStrings = EnpoStrings(
    productName = "ENPO Connect",
    organizationName = "البريد المصري",
    foundationEyebrow = "CONNECT",
    foundationTitle = "رفيقك الآمن لمنصة Connect",
    foundationBody = "هيكل ENPO Connect يعمل الآن داخل منصة Bot Global مع الحفاظ على هوية التطبيق.",
    sliceNotice = "هذه المرحلة تؤسس تجربة التطبيق فقط؛ الربط والإشعارات ستنتقل في مراحل مستقلة.",
    settings = "الإعدادات",
    language = "اللغة",
    appearance = "المظهر",
    about = "حول التطبيق",
    arabic = "العربية",
    english = "English",
    system = "النظام",
    light = "فاتح",
    dark = "داكن",
    back = "رجوع",
    version = "رقم الإصدار",
    platformFoundation = "أساس المنصة جاهز",
    platformFoundationBody = "اللغة والمظهر والتنقل والتخزين التفضيلي تستخدم قدرات المنصة المشتركة.",
    deferredCapabilities = "القدرات المؤجلة",
    deferredCapabilitiesBody = "لا يوجد اقتران أو Firebase أو إشعارات أو اتصال بالخلفية في هذه المرحلة.",
)

private val EnglishStrings = EnpoStrings(
    productName = "ENPO Connect",
    organizationName = "Egypt Post",
    foundationEyebrow = "CONNECT",
    foundationTitle = "Your secure Connect companion",
    foundationBody = "The ENPO Connect shell now runs inside Bot Global Platform while preserving its app identity.",
    sliceNotice = "This slice establishes the app experience only; pairing and notifications move in dedicated phases.",
    settings = "Settings",
    language = "Language",
    appearance = "Appearance",
    about = "About",
    arabic = "العربية",
    english = "English",
    system = "System",
    light = "Light",
    dark = "Dark",
    back = "Back",
    version = "Version",
    platformFoundation = "Platform foundation ready",
    platformFoundationBody = "Language, appearance, navigation, and preference storage use shared platform capabilities.",
    deferredCapabilities = "Capabilities intentionally deferred",
    deferredCapabilitiesBody = "Pairing, Firebase, notifications, and backend access are not included in this slice.",
)
