package com.enpo.connect.app.ui

import com.enpo.connect.app.state.EnpoBootstrapState
import com.enpo.connect.app.pairing.EnpoPairingError
import com.enpo.connect.app.pairing.EnpoPairingState

data class EnpoStrings(
    val productName: String,
    val organizationName: String,
    val loading: String,
    val home: String,
    val welcome: String,
    val linkedAndSecure: String,
    val authenticationRequests: String,
    val noAuthenticationRequests: String,
    val communications: String,
    val communicationsBody: String,
    val security: String,
    val securityBody: String,
    val foundationEyebrow: String,
    val foundationTitle: String,
    val foundationBody: String,
    val sliceNotice: String,
    val settings: String,
    val notifications: String,
    val notificationSettings: String,
    val enableNotifications: String,
    val enableNotificationsBody: String,
    val enpoSounds: String,
    val notificationInboxSubtitle: String,
    val noNotifications: String,
    val unread: String,
    val read: String,
    val highPriority: String,
    val normalPriority: String,
    val markAllRead: String,
    val viewDetails: String,
    val openAction: String,
    val actionUnavailable: String,
    val notificationDetails: String,
    val language: String,
    val appearance: String,
    val appearanceAndLanguage: String,
    val about: String,
    val deviceAndPairing: String,
    val deviceStatus: String,
    val pairingInformation: String,
    val pairedAndSecure: String,
    val pairingMode: String,
    val productionPublicService: String,
    val credentialStorage: String,
    val encryptedAndAvailable: String,
    val pairingProtectionTitle: String,
    val pairingCodeProtection: String,
    val pairingServerProtection: String,
    val unpairDevice: String,
    val unpairConfirmTitle: String,
    val unpairConfirmBody: String,
    val unpairCancel: String,
    val unpairWorking: String,
    val unpairFailureTitle: String,
    val unpairServiceUnavailable: String,
    val unpairLocalCleanupFailed: String,
    val unpairCredentialUnreadable: String,
    val unpairCompleted: String,
    val arabic: String,
    val english: String,
    val system: String,
    val light: String,
    val dark: String,
    val back: String,
    val version: String,
    val platformFoundation: String,
    val platformFoundationBody: String,
    val deviceState: String,
    val unpaired: String,
    val deviceCredentialAvailable: String,
    val credentialUnreadable: String,
    val initializationError: String,
    val pairingTitle: String,
    val pairingBody: String,
    val scanQr: String,
    val scannerPrompt: String,
    val scanning: String,
    val validating: String,
    val claiming: String,
    val persistingCredential: String,
    val retry: String,
    val pairingFailureTitle: String,
    val pairingSuccessTitle: String,
    val pairingSuccessBody: String,
    val continueToApp: String,
    val invalidQr: String,
    val unsupportedQr: String,
    val challengeUnavailable: String,
    val pairingUnauthorized: String,
    val networkUnavailable: String,
    val pairingTimeout: String,
    val serverUnavailable: String,
    val persistenceFailure: String,
    val cameraPermissionDenied: String,
    val cameraUnavailable: String,
    val scannerUnavailable: String,
    val pairingUnknown: String,
    val deferredCapabilities: String,
    val deferredCapabilitiesBody: String,
) {
    fun allValues(): List<String> = listOf(
        productName,
        organizationName,
        loading,
        home,
        welcome,
        linkedAndSecure,
        authenticationRequests,
        noAuthenticationRequests,
        communications,
        communicationsBody,
        security,
        securityBody,
        foundationEyebrow,
        foundationTitle,
        foundationBody,
        sliceNotice,
        settings,
        notifications,
        notificationSettings,
        enableNotifications,
        enableNotificationsBody,
        enpoSounds,
        notificationInboxSubtitle,
        noNotifications,
        unread,
        read,
        highPriority,
        normalPriority,
        markAllRead,
        viewDetails,
        openAction,
        notificationDetails,
        language,
        appearance,
        appearanceAndLanguage,
        about,
        deviceAndPairing,
        deviceStatus,
        pairingInformation,
        pairedAndSecure,
        pairingMode,
        productionPublicService,
        credentialStorage,
        encryptedAndAvailable,
        pairingProtectionTitle,
        pairingCodeProtection,
        pairingServerProtection,
        unpairDevice,
        unpairConfirmTitle,
        unpairConfirmBody,
        unpairCancel,
        unpairWorking,
        unpairFailureTitle,
        unpairServiceUnavailable,
        unpairLocalCleanupFailed,
        unpairCredentialUnreadable,
        unpairCompleted,
        arabic,
        english,
        system,
        light,
        dark,
        back,
        version,
        platformFoundation,
        platformFoundationBody,
        deviceState,
        unpaired,
        deviceCredentialAvailable,
        credentialUnreadable,
        initializationError,
        pairingTitle,
        pairingBody,
        scanQr,
        scannerPrompt,
        scanning,
        validating,
        claiming,
        persistingCredential,
        retry,
        pairingFailureTitle,
        pairingSuccessTitle,
        pairingSuccessBody,
        continueToApp,
        invalidQr,
        unsupportedQr,
        challengeUnavailable,
        pairingUnauthorized,
        networkUnavailable,
        pairingTimeout,
        serverUnavailable,
        persistenceFailure,
        cameraPermissionDenied,
        cameraUnavailable,
        scannerUnavailable,
        pairingUnknown,
        deferredCapabilities,
        deferredCapabilitiesBody,
    )

    fun deviceStateText(state: EnpoBootstrapState): String = when (state) {
        EnpoBootstrapState.Initializing -> platformFoundationBody
        EnpoBootstrapState.Unpaired -> unpaired
        EnpoBootstrapState.DeviceCredentialAvailable -> deviceCredentialAvailable
        EnpoBootstrapState.CredentialUnreadable -> credentialUnreadable
        EnpoBootstrapState.Error -> initializationError
    }

    fun pairingStateText(state: EnpoPairingState): String = when (state) {
        EnpoPairingState.Unpaired -> unpaired
        EnpoPairingState.Scanning -> scanning
        EnpoPairingState.Validating -> validating
        EnpoPairingState.Claiming -> claiming
        EnpoPairingState.PersistingCredential -> persistingCredential
        EnpoPairingState.Paired -> pairingSuccessBody
        is EnpoPairingState.RecoverableError -> pairingErrorText(state.error)
        is EnpoPairingState.FatalError -> pairingErrorText(state.error)
    }

    private fun pairingErrorText(error: EnpoPairingError): String = when (error) {
        EnpoPairingError.InvalidQr -> invalidQr
        EnpoPairingError.UnsupportedQr -> unsupportedQr
        EnpoPairingError.Expired,
        EnpoPairingError.AlreadyUsed,
        EnpoPairingError.InvalidExpiredOrAlreadyUsed,
        -> challengeUnavailable
        EnpoPairingError.Unauthorized,
        EnpoPairingError.Forbidden,
        -> pairingUnauthorized
        EnpoPairingError.NetworkUnavailable -> networkUnavailable
        EnpoPairingError.Timeout -> pairingTimeout
        EnpoPairingError.ServerUnavailable,
        EnpoPairingError.ServerError,
        -> serverUnavailable
        EnpoPairingError.PersistenceFailure -> persistenceFailure
        EnpoPairingError.CredentialUnreadable -> credentialUnreadable
        EnpoPairingError.CameraPermissionDenied -> cameraPermissionDenied
        EnpoPairingError.CameraUnavailable -> cameraUnavailable
        EnpoPairingError.ScannerUnavailable -> scannerUnavailable
        EnpoPairingError.Unknown -> pairingUnknown
    }
}

fun enpoStrings(languageTag: String): EnpoStrings =
    if (languageTag.startsWith("ar")) ArabicStrings else EnglishStrings

private val ArabicStrings = EnpoStrings(
    productName = "ENPO Connect",
    organizationName = "البريد المصري",
    loading = "جاري التحميل...",
    home = "الرئيسية",
    welcome = "مرحباً بك",
    linkedAndSecure = "الجهاز مرتبط وآمن",
    authenticationRequests = "طلبات المصادقة",
    noAuthenticationRequests = "لا توجد طلبات مصادقة حالياً",
    communications = "التعليمات والإشعارات",
    communicationsBody = "ستظهر هنا التعليمات الرسمية والتنبيهات المهمة الواردة من الجهة.",
    security = "الأمان والحماية",
    securityBody = "رمز الربط قصير الصلاحية، وبيانات اعتماد الجهاز محفوظة مشفّرة على هذا الهاتف.",
    foundationEyebrow = "CONNECT",
    foundationTitle = "رفيقك الآمن لمنصة Connect",
    foundationBody = "تطبيق البريد المصري المرتبط بحسابك في Connect.",
    sliceNotice = "الجهاز مرتبط وجاهز لاستقبال إشعارات ENPO Connect.",
    settings = "الإعدادات",
    notifications = "الإشعارات",
    notificationSettings = "إعدادات الإشعارات",
    enableNotifications = "تفعيل الإشعارات",
    enableNotificationsBody = "استقبال التنبيهات والتعليمات الرسمية",
    enpoSounds = "أصوات ENPO Connect",
    notificationInboxSubtitle = "التعليمات والتنبيهات الواردة من الجهة",
    noNotifications = "لا توجد إشعارات حالياً.",
    unread = "غير مقروء",
    read = "مقروء",
    highPriority = "أولوية عالية",
    normalPriority = "أولوية عادية",
    markAllRead = "قراءة الكل",
    viewDetails = "عرض التفاصيل",
    openAction = "فتح الرابط",
    actionUnavailable = "رابط هذا الإشعار لم يعد متاحًا.",
    notificationDetails = "تفاصيل الإشعار",
    language = "اللغة",
    appearance = "المظهر",
    appearanceAndLanguage = "المظهر واللغة",
    about = "حول التطبيق",
    deviceAndPairing = "الجهاز والاقتران",
    deviceStatus = "حالة الجهاز",
    pairingInformation = "حماية الاقتران وإلغاؤه",
    pairedAndSecure = "مقترن وآمن",
    pairingMode = "وضع الاقتران",
    productionPublicService = "مرتبط بحساب Connect",
    credentialStorage = "بيانات اعتماد الجهاز",
    encryptedAndAvailable = "محفوظة مشفّرة على هذا الهاتف",
    pairingProtectionTitle = "كيف نحمي اقترانك؟",
    pairingCodeProtection = "رمز QR مؤقت ويُستخدم مرة واحدة لربط هذا الهاتف بحسابك.",
    pairingServerProtection = "إلغاء الاقتران يلغي اعتماد هذا الجهاز على الخدمة ويوقف وصول الإشعارات الجديدة إليه.",
    unpairDevice = "إلغاء اقتران هذا الهاتف",
    unpairConfirmTitle = "إلغاء اقتران هذا الهاتف؟",
    unpairConfirmBody = "سيتوقف وصول إشعارات ENPO Connect إلى هذا الهاتف، وستُحذف الإشعارات المحفوظة عليه. ستحتاج إلى رمز QR جديد لاستخدام التطبيق مرة أخرى.",
    unpairCancel = "الاحتفاظ بالاقتران",
    unpairWorking = "جارٍ إلغاء الاقتران…",
    unpairFailureTitle = "لم يكتمل إلغاء الاقتران",
    unpairServiceUnavailable = "تعذر تأكيد إلغاء الاقتران الآن. أُوقفت الإشعارات مؤقتًا لحماية بياناتك؛ تحقق من الاتصال ثم حاول مرة أخرى، أو افتح التطبيق لاحقًا لإعادة المحاولة.",
    unpairLocalCleanupFailed = "أُلغي اعتماد الجهاز على الخدمة، لكن تعذر حذف بياناته من الهاتف. حاول مرة أخرى.",
    unpairCredentialUnreadable = "تعذر قراءة بيانات اقتران هذا الهاتف. لم تُحذف البيانات؛ تواصل مع الدعم.",
    unpairCompleted = "تم إلغاء اقتران هذا الهاتف. يمكنك ربطه مجدداً برمز QR جديد.",
    arabic = "العربية",
    english = "English",
    system = "النظام",
    light = "فاتح",
    dark = "داكن",
    back = "رجوع",
    version = "رقم الإصدار",
    platformFoundation = "أساس المنصة جاهز",
    platformFoundationBody = "اللغة والمظهر والتنقل والتخزين التفضيلي تستخدم قدرات المنصة المشتركة.",
    deviceState = "حالة الجهاز",
    unpaired = "هذا الجهاز غير مرتبط بعد.",
    deviceCredentialAvailable = "تم ربط هذا الجهاز بحساب Connect، وبيانات الربط محفوظة بأمان.",
    credentialUnreadable = "توجد بيانات جهاز لا يمكن قراءتها بأمان؛ لم يتم حذفها أو استبدالها.",
    initializationError = "تعذر فحص حالة الجهاز محلياً.",
    pairingTitle = "اربط هذا الجهاز بمنصة Connect",
    pairingBody = "افتح Connect V2 واعرض رمز الربط المؤقت، ثم اسمح بالكاميرا وامسح الرمز. لا يحتوي الرمز على بياناتك الشخصية.",
    scanQr = "مسح رمز QR",
    scannerPrompt = "ضع رمز ربط Connect داخل الإطار",
    scanning = "الكاميرا مفتوحة لقراءة رمز الربط فقط.",
    validating = "جارٍ التحقق من صيغة الرمز…",
    claiming = "جارٍ تأكيد الربط مع Connect…",
    persistingCredential = "جارٍ حفظ بيانات الجهاز بصورة مشفرة…",
    retry = "المحاولة مرة أخرى",
    pairingFailureTitle = "لم يكتمل ربط الجهاز",
    pairingSuccessTitle = "تم ربط الجهاز بنجاح",
    pairingSuccessBody = "أصبح هذا الجهاز مرتبطاً بحسابك في Connect. يمكنك الآن متابعة استخدام التطبيق.",
    continueToApp = "الدخول إلى ENPO Connect",
    invalidQr = "رمز QR غير صالح. اعرض رمز ربط جديد من Connect V2.",
    unsupportedQr = "هذا الرمز ليس رمز ربط Connect V2.",
    challengeUnavailable = "انتهت صلاحية رمز الربط أو سبق استخدامه أو لم يعد صالحاً. أنشئ رمزاً جديداً.",
    pairingUnauthorized = "خدمة الربط رفضت الطلب. حاول لاحقاً أو تواصل مع الدعم.",
    networkUnavailable = "تعذر الوصول إلى الشبكة. تحقق من الاتصال ثم حاول مرة أخرى.",
    pairingTimeout = "انتهت مهلة الاتصال. تحقق من الشبكة ثم حاول مرة أخرى.",
    serverUnavailable = "خدمة الربط غير متاحة مؤقتاً. حاول مرة أخرى لاحقاً.",
    persistenceFailure = "اكتمل رد الخدمة لكن تعذر تأمين بيانات الجهاز. لا تحذف التطبيق وتواصل مع الدعم.",
    cameraPermissionDenied = "يلزم السماح بالكاميرا لمسح الرمز. فعّل الإذن من إعدادات الجهاز إذا كان محظوراً.",
    cameraUnavailable = "الكاميرا غير متاحة على هذا الجهاز.",
    scannerUnavailable = "تعذر فتح ماسح QR. أغلق التطبيقات التي تستخدم الكاميرا ثم حاول مرة أخرى.",
    pairingUnknown = "تعذر إكمال الربط بأمان. حاول مرة أخرى.",
    deferredCapabilities = "القدرات المؤجلة",
    deferredCapabilitiesBody = "يمكنك مراجعة حالة الاقتران وإلغائه من إعدادات الجهاز.",
)

private val EnglishStrings = EnpoStrings(
    productName = "ENPO Connect",
    organizationName = "Egypt Post",
    loading = "Loading...",
    home = "Home",
    welcome = "Welcome",
    linkedAndSecure = "Device linked and secure",
    authenticationRequests = "Authentication requests",
    noAuthenticationRequests = "There are no authentication requests right now",
    communications = "Instructions & notifications",
    communicationsBody = "Official instructions and important organization alerts will appear here.",
    security = "Security & protection",
    securityBody = "The pairing code expires quickly, and this phone stores its device credential encrypted.",
    foundationEyebrow = "CONNECT",
    foundationTitle = "Your secure Connect companion",
    foundationBody = "The Egypt Post app linked to your Connect account.",
    sliceNotice = "This paired device is ready to receive ENPO Connect notifications.",
    settings = "Settings",
    notifications = "Notifications",
    notificationSettings = "Notification settings",
    enableNotifications = "Enable notifications",
    enableNotificationsBody = "Receive official alerts and instructions",
    enpoSounds = "ENPO Connect sounds",
    notificationInboxSubtitle = "Instructions and alerts from your organization",
    noNotifications = "There are no notifications yet.",
    unread = "Unread",
    read = "Read",
    highPriority = "High priority",
    normalPriority = "Normal priority",
    markAllRead = "Read all",
    viewDetails = "View details",
    openAction = "Open link",
    actionUnavailable = "This notification link is no longer available.",
    notificationDetails = "Notification details",
    language = "Language",
    appearance = "Appearance",
    appearanceAndLanguage = "Appearance & language",
    about = "About",
    deviceAndPairing = "Device & pairing",
    deviceStatus = "Device status",
    pairingInformation = "Pairing security & unpair",
    pairedAndSecure = "Paired and secure",
    pairingMode = "Pairing mode",
    productionPublicService = "Linked to your Connect account",
    credentialStorage = "Device credential",
    encryptedAndAvailable = "Stored encrypted on this phone",
    pairingProtectionTitle = "How is pairing protected?",
    pairingCodeProtection = "The QR code is temporary and can be used once to pair this phone with your account.",
    pairingServerProtection = "Unpairing revokes this device's access to the service and stops new notifications to it.",
    unpairDevice = "Unpair this phone",
    unpairConfirmTitle = "Unpair this phone?",
    unpairConfirmBody = "ENPO Connect notifications will stop on this phone, and notifications saved here will be deleted. You will need a new QR code to use the app again.",
    unpairCancel = "Keep paired",
    unpairWorking = "Unpairing…",
    unpairFailureTitle = "Unpairing did not finish",
    unpairServiceUnavailable = "Unpairing could not be confirmed. Notifications are paused to protect your data. Check your connection and try again, or reopen the app to retry.",
    unpairLocalCleanupFailed = "The service revoked this device, but local data could not be removed. Try again.",
    unpairCredentialUnreadable = "This phone's pairing data could not be read. Nothing was deleted; contact support.",
    unpairCompleted = "This phone is unpaired. You can pair it again with a new QR code.",
    arabic = "العربية",
    english = "English",
    system = "System",
    light = "Light",
    dark = "Dark",
    back = "Back",
    version = "Version",
    platformFoundation = "Platform foundation ready",
    platformFoundationBody = "Language, appearance, navigation, and preference storage use shared platform capabilities.",
    deviceState = "Device state",
    unpaired = "This device is not paired yet.",
    deviceCredentialAvailable = "This device is paired with your Connect account, and its pairing data is stored securely.",
    credentialUnreadable = "Device data exists but cannot be read safely; it was not removed or replaced.",
    initializationError = "The local device state could not be inspected.",
    pairingTitle = "Pair this device with Connect",
    pairingBody = "Open Connect V2 and display a fresh temporary pairing code, then allow camera access and scan it. The code contains no personal information.",
    scanQr = "Scan QR code",
    scannerPrompt = "Place the Connect pairing code inside the frame",
    scanning = "The camera is open only to read the pairing code.",
    validating = "Validating the code format…",
    claiming = "Confirming pairing with Connect…",
    persistingCredential = "Saving encrypted device data…",
    retry = "Try again",
    pairingFailureTitle = "Device pairing did not finish",
    pairingSuccessTitle = "Device paired successfully",
    pairingSuccessBody = "This device is now paired with your Connect account. You can continue using the app.",
    continueToApp = "Enter ENPO Connect",
    invalidQr = "This QR code is invalid. Display a fresh pairing code from Connect V2.",
    unsupportedQr = "This is not a Connect V2 pairing code.",
    challengeUnavailable = "This pairing code expired, was already used, or is no longer valid. Create a fresh code.",
    pairingUnauthorized = "The pairing service rejected the request. Try later or contact support.",
    networkUnavailable = "The network is unavailable. Check the connection and try again.",
    pairingTimeout = "The connection timed out. Check the network and try again.",
    serverUnavailable = "The pairing service is temporarily unavailable. Try again later.",
    persistenceFailure = "The service replied, but device data could not be secured. Keep the app installed and contact support.",
    cameraPermissionDenied = "Camera permission is required. Enable it in device settings if it is blocked.",
    cameraUnavailable = "The camera is unavailable on this device.",
    scannerUnavailable = "The QR scanner could not open. Close other camera apps and try again.",
    pairingUnknown = "Pairing could not be completed safely. Try again.",
    deferredCapabilities = "Capabilities intentionally deferred",
    deferredCapabilitiesBody = "You can review pairing status and unpair from device settings.",
)
