// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using SentriCam.Infrastructure.Persistence;

#nullable disable

namespace SentriCam.Migrations.PostgreSql.Migrations
{
    [DbContext(typeof(SentriCamDbContext))]
    partial class SentriCamDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.25")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("SentriCam.Application.Messaging.OutboxMessage", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<int>("AttemptCount")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasPrecision(7)
                        .HasColumnType("timestamp(7) with time zone");

                    b.Property<Guid>("EventId")
                        .HasColumnType("uuid");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<DateTimeOffset>("OccurredAtUtc")
                        .HasPrecision(7)
                        .HasColumnType("timestamp(7) with time zone");

                    b.Property<string>("PayloadJson")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset?>("ProcessedAtUtc")
                        .HasPrecision(7)
                        .HasColumnType("timestamp(7) with time zone");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .HasColumnType("bytea");

                    b.Property<int>("SchemaVersion")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("EventId")
                        .IsUnique()
                        .HasDatabaseName("UX_OutboxMessages_EventId");

                    b.HasIndex("ProcessedAtUtc", "CreatedAtUtc")
                        .HasDatabaseName("IX_OutboxMessages_ProcessedAtUtc_CreatedAtUtc");

                    b.ToTable("OutboxMessages", (string)null);
                });

            modelBuilder.Entity("SentriCam.Domain.Devices.Device", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("DeviceGroupId")
                        .HasColumnType("uuid");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<bool>("IsEnabled")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset?>("LastSeenAtUtc")
                        .HasPrecision(7)
                        .HasColumnType("timestamp(7) with time zone");

                    b.Property<DateTimeOffset>("RegisteredAtUtc")
                        .HasPrecision(7)
                        .HasColumnType("timestamp(7) with time zone");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .HasColumnType("bytea");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("UpdatedAtUtc")
                        .HasPrecision(7)
                        .HasColumnType("timestamp(7) with time zone");

                    b.HasKey("Id");

                    b.HasIndex("DeviceGroupId")
                        .HasDatabaseName("IX_Devices_DeviceGroupId");

                    b.HasIndex("Status", "LastSeenAtUtc")
                        .HasDatabaseName("IX_Devices_Status_LastSeenAtUtc");

                    b.ToTable("Devices", (string)null);
                });

            modelBuilder.Entity("SentriCam.Domain.Devices.DeviceCapability", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("AddedAtUtc")
                        .HasPrecision(7)
                        .HasColumnType("timestamp(7) with time zone");

                    b.Property<Guid>("DeviceId")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsEnabled")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("NormalizedName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTimeOffset>("UpdatedAtUtc")
                        .HasPrecision(7)
                        .HasColumnType("timestamp(7) with time zone");

                    b.Property<string>("Version")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id");

                    b.HasIndex("DeviceId", "NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("UX_DeviceCapabilities_DeviceId_NormalizedName");

                    b.ToTable("DeviceCapabilities", (string)null);
                });

            modelBuilder.Entity("SentriCam.Domain.Devices.DeviceCommand", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset?>("CompletedAtUtc")
                        .HasPrecision(7)
                        .HasColumnType("timestamp(7) with time zone");

                    b.Property<string>("CorrelationId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<Guid>("DeviceId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset?>("DispatchedAtUtc")
                        .HasPrecision(7)
                        .HasColumnType("timestamp(7) with time zone");

                    b.Property<DateTimeOffset?>("ExpiresAtUtc")
                        .HasPrecision(7)
                        .HasColumnType("timestamp(7) with time zone");

                    b.Property<string>("FailureReason")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<int>("Kind")
                        .HasColumnType("integer");

                    b.Property<int>("Origin")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("RequestedAtUtc")
                        .HasPrecision(7)
                        .HasColumnType("timestamp(7) with time zone");

                    b.Property<string>("ResultCode")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("ResultJson")
                        .HasColumnType("text");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .HasColumnType("bytea");

                    b.Property<int>("State")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("DeviceId", "CorrelationId")
                        .IsUnique()
                        .HasDatabaseName("UX_DeviceCommands_DeviceId_CorrelationId");

                    b.HasIndex("DeviceId", "State", "RequestedAtUtc")
                        .IsDescending(false, false, true)
                        .HasDatabaseName("IX_DeviceCommands_DeviceId_State_RequestedAtUtc");

                    b.ToTable("DeviceCommands", (string)null);
                });

            modelBuilder.Entity("SentriCam.Domain.Devices.DeviceConnection", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("ConnectedAtUtc")
                        .HasPrecision(7)
                        .HasColumnType("timestamp(7) with time zone");

                    b.Property<Guid>("DeviceId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset?>("DisconnectedAtUtc")
                        .HasPrecision(7)
                        .HasColumnType("timestamp(7) with time zone");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset>("LastSeenAtUtc")
                        .HasPrecision(7)
                        .HasColumnType("timestamp(7) with time zone");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .HasColumnType("bytea");

                    b.Property<string>("TransportConnectionId")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.HasKey("Id");

                    b.HasIndex("TransportConnectionId")
                        .IsUnique()
                        .HasDatabaseName("UX_DeviceConnections_TransportConnectionId");

                    b.HasIndex("DeviceId", "IsActive")
                        .IsUnique()
                        .HasDatabaseName("UX_DeviceConnections_OneActivePerDevice")
                        .HasFilter("\"IsActive\" = TRUE");

                    b.HasIndex("DeviceId", "LastSeenAtUtc")
                        .IsDescending(false, true)
                        .HasDatabaseName("IX_DeviceConnections_DeviceId_LastSeenAtUtc");

                    b.ToTable("DeviceConnections", (string)null);
                });

            modelBuilder.Entity("SentriCam.Domain.Devices.DeviceEvent", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<Guid>("DeviceId")
                        .HasColumnType("uuid");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTimeOffset>("OccurredAtUtc")
                        .HasPrecision(7)
                        .HasColumnType("timestamp(7) with time zone");

                    b.Property<string>("PayloadJson")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("ReceivedAtUtc")
                        .HasPrecision(7)
                        .HasColumnType("timestamp(7) with time zone");

                    b.HasKey("Id");

                    b.HasIndex("DeviceId", "OccurredAtUtc")
                        .IsDescending(false, true)
                        .HasDatabaseName("IX_DeviceEvents_DeviceId_OccurredAtUtc");

                    b.HasIndex("EventType", "ReceivedAtUtc")
                        .IsDescending(false, true)
                        .HasDatabaseName("IX_DeviceEvents_EventType_ReceivedAtUtc");

                    b.ToTable("DeviceEvents", (string)null);
                });

            modelBuilder.Entity("SentriCam.Domain.Devices.DeviceRegistration", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<string>("ClientAppVersion")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<Guid>("DeviceId")
                        .HasColumnType("uuid");

                    b.Property<int>("Kind")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("RegisteredAtUtc")
                        .HasPrecision(7)
                        .HasColumnType("timestamp(7) with time zone");

                    b.HasKey("Id");

                    b.HasIndex("DeviceId", "RegisteredAtUtc")
                        .IsDescending(false, true)
                        .HasDatabaseName("IX_DeviceRegistrations_DeviceId_RegisteredAtUtc");

                    b.ToTable("DeviceRegistrations", (string)null);
                });

            modelBuilder.Entity("SentriCam.Domain.Devices.DeviceSnapshot", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<long?>("AvailableStorageBytes")
                        .HasColumnType("bigint");

                    b.Property<int?>("BatteryPercentage")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("CapturedAtUtc")
                        .HasPrecision(7)
                        .HasColumnType("timestamp(7) with time zone");

                    b.Property<Guid>("DeviceId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("GeneratedAtUtc")
                        .HasPrecision(7)
                        .HasColumnType("timestamp(7) with time zone");

                    b.Property<bool>("IsMonitoring")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsRecording")
                        .HasColumnType("boolean");

                    b.Property<string>("MetadataJson")
                        .HasColumnType("text");

                    b.Property<int>("SchemaVersion")
                        .HasColumnType("integer");

                    b.Property<long>("SnapshotVersion")
                        .HasColumnType("bigint");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("DeviceId", "CapturedAtUtc")
                        .IsDescending(false, true)
                        .HasDatabaseName("IX_DeviceSnapshots_DeviceId_CapturedAtUtc");

                    b.HasIndex("DeviceId", "SnapshotVersion")
                        .IsUnique()
                        .HasDatabaseName("UX_DeviceSnapshots_DeviceId_SnapshotVersion");

                    b.ToTable("DeviceSnapshots", (string)null);
                });

            modelBuilder.Entity("SentriCam.Domain.Devices.DeviceStatusHistory", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("ChangedAtUtc")
                        .HasPrecision(7)
                        .HasColumnType("timestamp(7) with time zone");

                    b.Property<int>("CurrentStatus")
                        .HasColumnType("integer");

                    b.Property<Guid>("DeviceId")
                        .HasColumnType("uuid");

                    b.Property<int?>("PreviousStatus")
                        .HasColumnType("integer");

                    b.Property<string>("Reason")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.HasKey("Id");

                    b.HasIndex("DeviceId", "ChangedAtUtc")
                        .IsDescending(false, true)
                        .HasDatabaseName("IX_DeviceStatusHistory_DeviceId_ChangedAtUtc");

                    b.ToTable("DeviceStatusHistory", (string)null);
                });

            modelBuilder.Entity("SentriCam.Domain.Hierarchy.Area", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasPrecision(7)
                        .HasColumnType("timestamp(7) with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .HasColumnType("bytea");

                    b.Property<Guid>("SiteId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("SiteId", "Name")
                        .IsUnique()
                        .HasDatabaseName("UX_Areas_SiteId_Name");

                    b.ToTable("Areas", (string)null);
                });

            modelBuilder.Entity("SentriCam.Domain.Hierarchy.DeviceGroup", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<Guid>("AreaId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasPrecision(7)
                        .HasColumnType("timestamp(7) with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .HasColumnType("bytea");

                    b.HasKey("Id");

                    b.HasIndex("AreaId", "Name")
                        .IsUnique()
                        .HasDatabaseName("UX_DeviceGroups_AreaId_Name");

                    b.ToTable("DeviceGroups", (string)null);
                });

            modelBuilder.Entity("SentriCam.Domain.Hierarchy.Organization", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasPrecision(7)
                        .HasColumnType("timestamp(7) with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .HasColumnType("bytea");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasDatabaseName("UX_Organizations_Name");

                    b.ToTable("Organizations", (string)null);
                });

            modelBuilder.Entity("SentriCam.Domain.Hierarchy.Site", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasPrecision(7)
                        .HasColumnType("timestamp(7) with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<Guid>("OrganizationId")
                        .HasColumnType("uuid");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .HasColumnType("bytea");

                    b.HasKey("Id");

                    b.HasIndex("OrganizationId", "Name")
                        .IsUnique()
                        .HasDatabaseName("UX_Sites_OrganizationId_Name");

                    b.ToTable("Sites", (string)null);
                });

            modelBuilder.Entity("SentriCam.Domain.Recordings.Recording", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<string>("ChecksumSha256")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("ClientRecordingId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("ContentType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTimeOffset>("CreatedUtc")
                        .HasPrecision(7)
                        .HasColumnType("timestamp(7) with time zone");

                    b.Property<Guid>("DeviceId")
                        .HasColumnType("uuid");

                    b.Property<long>("DurationMilliseconds")
                        .HasColumnType("bigint");

                    b.Property<bool>("IsManual")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsMotion")
                        .HasColumnType("boolean");

                    b.Property<string>("OriginalFileName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("RelativePath")
                        .IsRequired()
                        .HasMaxLength(1024)
                        .HasColumnType("character varying(1024)");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .HasColumnType("bytea");

                    b.Property<string>("SessionId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<long>("SizeBytes")
                        .HasColumnType("bigint");

                    b.Property<string>("ThumbnailErrorCode")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTimeOffset?>("ThumbnailGeneratedUtc")
                        .HasPrecision(7)
                        .HasColumnType("timestamp(7) with time zone");

                    b.Property<int>("ThumbnailGenerationAttempts")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset?>("ThumbnailProcessingStartedUtc")
                        .HasPrecision(7)
                        .HasColumnType("timestamp(7) with time zone");

                    b.Property<string>("ThumbnailRelativePath")
                        .HasMaxLength(1024)
                        .HasColumnType("character varying(1024)");

                    b.Property<int>("ThumbnailState")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("UploadedUtc")
                        .HasPrecision(7)
                        .HasColumnType("timestamp(7) with time zone");

                    b.HasKey("Id");

                    b.HasIndex("ChecksumSha256")
                        .HasDatabaseName("IX_Recordings_ChecksumSha256");

                    b.HasIndex("CreatedUtc")
                        .IsDescending()
                        .HasDatabaseName("IX_Recordings_CreatedUtc");

                    b.HasIndex("UploadedUtc")
                        .IsDescending()
                        .HasDatabaseName("IX_Recordings_UploadedUtc");

                    b.HasIndex("DeviceId", "ClientRecordingId")
                        .IsUnique()
                        .HasDatabaseName("UX_Recordings_DeviceId_ClientRecordingId");

                    b.HasIndex("DeviceId", "CreatedUtc")
                        .IsDescending(false, true)
                        .HasDatabaseName("IX_Recordings_DeviceId_CreatedUtc");

                    b.HasIndex("DurationMilliseconds", "CreatedUtc")
                        .HasDatabaseName("IX_Recordings_DurationMilliseconds_CreatedUtc");

                    b.HasIndex("IsMotion", "CreatedUtc")
                        .HasDatabaseName("IX_Recordings_IsMotion_CreatedUtc");

                    b.HasIndex("SizeBytes", "CreatedUtc")
                        .HasDatabaseName("IX_Recordings_SizeBytes_CreatedUtc");

                    b.HasIndex("ThumbnailState", "UploadedUtc")
                        .HasDatabaseName("IX_Recordings_ThumbnailState_UploadedUtc");

                    b.ToTable("Recordings", (string)null);
                });

            modelBuilder.Entity("SentriCam.Domain.Devices.Device", b =>
                {
                    b.HasOne("SentriCam.Domain.Hierarchy.DeviceGroup", null)
                        .WithMany()
                        .HasForeignKey("DeviceGroupId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.OwnsOne("SentriCam.Domain.Devices.DeviceIdentity", "Identity", b1 =>
                        {
                            b1.Property<Guid>("DeviceId")
                                .HasColumnType("uuid");

                            b1.Property<string>("AppVersion")
                                .IsRequired()
                                .HasMaxLength(50)
                                .HasColumnType("character varying(50)")
                                .HasColumnName("AppVersion");

                            b1.Property<string>("InstallationId")
                                .IsRequired()
                                .HasMaxLength(128)
                                .HasColumnType("character varying(128)")
                                .HasColumnName("InstallationId");

                            b1.Property<string>("Manufacturer")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("character varying(100)")
                                .HasColumnName("Manufacturer");

                            b1.Property<string>("Model")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("character varying(100)")
                                .HasColumnName("Model");

                            b1.Property<string>("OperatingSystemVersion")
                                .IsRequired()
                                .HasMaxLength(50)
                                .HasColumnType("character varying(50)")
                                .HasColumnName("OperatingSystemVersion");

                            b1.Property<string>("Platform")
                                .IsRequired()
                                .HasMaxLength(50)
                                .HasColumnType("character varying(50)")
                                .HasColumnName("Platform");

                            b1.HasKey("DeviceId");

                            b1.HasIndex("InstallationId")
                                .IsUnique()
                                .HasDatabaseName("UX_Devices_InstallationId");

                            b1.ToTable("Devices");

                            b1.WithOwner()
                                .HasForeignKey("DeviceId");
                        });

                    b.Navigation("Identity")
                        .IsRequired();
                });

            modelBuilder.Entity("SentriCam.Domain.Devices.DeviceCapability", b =>
                {
                    b.HasOne("SentriCam.Domain.Devices.Device", null)
                        .WithMany("Capabilities")
                        .HasForeignKey("DeviceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("SentriCam.Domain.Devices.DeviceCommand", b =>
                {
                    b.HasOne("SentriCam.Domain.Devices.Device", null)
                        .WithMany()
                        .HasForeignKey("DeviceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("SentriCam.Domain.Devices.DeviceConnection", b =>
                {
                    b.HasOne("SentriCam.Domain.Devices.Device", null)
                        .WithMany()
                        .HasForeignKey("DeviceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("SentriCam.Domain.Devices.DeviceEvent", b =>
                {
                    b.HasOne("SentriCam.Domain.Devices.Device", null)
                        .WithMany()
                        .HasForeignKey("DeviceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("SentriCam.Domain.Devices.DeviceRegistration", b =>
                {
                    b.HasOne("SentriCam.Domain.Devices.Device", null)
                        .WithMany()
                        .HasForeignKey("DeviceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("SentriCam.Domain.Devices.DeviceSnapshot", b =>
                {
                    b.HasOne("SentriCam.Domain.Devices.Device", null)
                        .WithMany()
                        .HasForeignKey("DeviceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("SentriCam.Domain.Devices.DeviceStatusHistory", b =>
                {
                    b.HasOne("SentriCam.Domain.Devices.Device", null)
                        .WithMany()
                        .HasForeignKey("DeviceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("SentriCam.Domain.Hierarchy.Area", b =>
                {
                    b.HasOne("SentriCam.Domain.Hierarchy.Site", null)
                        .WithMany()
                        .HasForeignKey("SiteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("SentriCam.Domain.Hierarchy.DeviceGroup", b =>
                {
                    b.HasOne("SentriCam.Domain.Hierarchy.Area", null)
                        .WithMany()
                        .HasForeignKey("AreaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("SentriCam.Domain.Hierarchy.Site", b =>
                {
                    b.HasOne("SentriCam.Domain.Hierarchy.Organization", null)
                        .WithMany()
                        .HasForeignKey("OrganizationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("SentriCam.Domain.Recordings.Recording", b =>
                {
                    b.HasOne("SentriCam.Domain.Devices.Device", null)
                        .WithMany()
                        .HasForeignKey("DeviceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("SentriCam.Domain.Devices.Device", b =>
                {
                    b.Navigation("Capabilities");
                });
#pragma warning restore 612, 618
        }
    }
}
