// <auto-generated />
using System;
using BotGlobal.Calling.Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BotGlobal.Calling.Infrastructure.Migrations
{
    [DbContext(typeof(CallingDbContext))]
    [Migration("20260901134012_AddCommunicationActivity")]
    partial class AddCommunicationActivity
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("BotGlobal.Calling.Domain.CallParticipantRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset?>("AnsweredAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<Guid>("CallId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("DisplayNameSnapshot")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("nvarchar(160)");

                    b.Property<DateTimeOffset?>("JoinedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<Guid>("MembershipId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(16)
                        .IsUnicode(false)
                        .HasColumnType("varchar(16)");

                    b.HasKey("Id");

                    b.HasIndex("MembershipId", "CallId");

                    b.ToTable("CallParticipants", "calling");
                });

            modelBuilder.Entity("BotGlobal.Calling.Domain.CallRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset?>("AnsweredAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<Guid>("ApplicationId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ApplicationKey")
                        .IsRequired()
                        .HasMaxLength(80)
                        .IsUnicode(false)
                        .HasColumnType("varchar(80)");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("EndReason")
                        .HasMaxLength(40)
                        .IsUnicode(false)
                        .HasColumnType("varchar(40)");

                    b.Property<DateTimeOffset?>("EndedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Outcome")
                        .HasMaxLength(16)
                        .IsUnicode(false)
                        .HasColumnType("varchar(16)");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasMaxLength(16)
                        .IsUnicode(false)
                        .HasColumnType("varchar(16)");

                    b.HasKey("Id");

                    b.HasIndex("ApplicationId", "CreatedAtUtc");

                    b.ToTable("Calls", "calling");
                });

            modelBuilder.Entity("BotGlobal.Calling.Domain.CallUsageReport", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<long>("BytesReceived")
                        .HasColumnType("bigint");

                    b.Property<long>("BytesSent")
                        .HasColumnType("bigint");

                    b.Property<Guid>("CallId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<long>("ConnectedDurationSeconds")
                        .HasColumnType("bigint");

                    b.Property<DateTimeOffset>("FinalizedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<Guid>("MembershipId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("CallId", "MembershipId")
                        .IsUnique();

                    b.HasIndex("MembershipId", "FinalizedAtUtc");

                    b.ToTable("CallUsageReports", "calling", t =>
                        {
                            t.HasCheckConstraint("CK_CallUsageReports_NonNegative", "[BytesSent] >= 0 AND [BytesReceived] >= 0 AND [ConnectedDurationSeconds] >= 0");
                        });
                });

            modelBuilder.Entity("BotGlobal.Calling.Domain.UsageCounterPeriod", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ApplicationId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset?>("EndedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<Guid>("MembershipId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ResetReason")
                        .IsRequired()
                        .HasMaxLength(16)
                        .IsUnicode(false)
                        .HasColumnType("varchar(16)");

                    b.Property<DateTime?>("ScheduledLocalDateTime")
                        .HasColumnType("datetime2");

                    b.Property<DateTimeOffset?>("ScheduledResetAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("ScheduledTimeZoneId")
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)");

                    b.Property<DateTimeOffset>("StartedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.HasKey("Id");

                    b.HasIndex("ApplicationId", "MembershipId")
                        .IsUnique()
                        .HasFilter("[EndedAtUtc] IS NULL");

                    b.HasIndex("ApplicationId", "MembershipId", "StartedAtUtc");

                    b.ToTable("UsageCounterPeriods", "calling");
                });

            modelBuilder.Entity("BotGlobal.Calling.Domain.CallParticipantRecord", b =>
                {
                    b.HasOne("BotGlobal.Calling.Domain.CallRecord", null)
                        .WithMany("Participants")
                        .HasForeignKey("CallId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("BotGlobal.Calling.Domain.CallUsageReport", b =>
                {
                    b.HasOne("BotGlobal.Calling.Domain.CallRecord", null)
                        .WithMany("UsageReports")
                        .HasForeignKey("CallId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BotGlobal.Calling.Domain.CallParticipantRecord", null)
                        .WithMany()
                        .HasForeignKey("CallId", "MembershipId")
                        .HasPrincipalKey("CallId", "MembershipId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();
                });

            modelBuilder.Entity("BotGlobal.Calling.Domain.CallRecord", b =>
                {
                    b.Navigation("Participants");

                    b.Navigation("UsageReports");
                });
#pragma warning restore 612, 618
        }
    }
}
