// <auto-generated />
using System;
using BotGlobal.PlatformClients.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BotGlobal.PlatformClients.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(PlatformClientsDbContext))]
    partial class PlatformClientsDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("platform_clients")
                .HasAnnotation("ProductVersion", "10.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("BotGlobal.PlatformClients.Domain.PlatformClient", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ClientKey")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset?>("DisabledAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(16)
                        .IsUnicode(false)
                        .HasColumnType("varchar(16)");

                    b.HasKey("Id");

                    b.HasIndex("ClientKey")
                        .IsUnique()
                        .HasDatabaseName("UX_PlatformClients_ClientKey");

                    b.ToTable("Clients", "platform_clients", t =>
                        {
                            t.HasCheckConstraint("CK_PlatformClients_Status", "[Status] IN ('Active','Disabled')");
                        });
                });

            modelBuilder.Entity("BotGlobal.PlatformClients.Domain.PlatformClientCapability", b =>
                {
                    b.Property<Guid>("ClientId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Capability")
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)");

                    b.Property<DateTimeOffset>("GrantedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.HasKey("ClientId", "Capability");

                    b.ToTable("Capabilities", "platform_clients");
                });

            modelBuilder.Entity("BotGlobal.PlatformClients.Domain.PlatformClientCredential", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ClientId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset?>("ExpiresAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset?>("RevokedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<byte[]>("SecretHash")
                        .IsRequired()
                        .HasColumnType("binary(32)");

                    b.HasKey("Id");

                    b.HasIndex("ClientId", "RevokedAtUtc", "ExpiresAtUtc")
                        .HasDatabaseName("IX_PlatformClientCredentials_Client_Usability");

                    b.ToTable("Credentials", "platform_clients", t =>
                        {
                            t.HasCheckConstraint("CK_PlatformClientCredentials_Expiry", "[ExpiresAtUtc] IS NULL OR [ExpiresAtUtc] > [CreatedAtUtc]");

                            t.HasCheckConstraint("CK_PlatformClientCredentials_RevokeTime", "[RevokedAtUtc] IS NULL OR [RevokedAtUtc] >= [CreatedAtUtc]");
                        });
                });

            modelBuilder.Entity("BotGlobal.PlatformClients.Domain.PlatformClientCapability", b =>
                {
                    b.HasOne("BotGlobal.PlatformClients.Domain.PlatformClient", null)
                        .WithMany("Capabilities")
                        .HasForeignKey("ClientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("BotGlobal.PlatformClients.Domain.PlatformClientCredential", b =>
                {
                    b.HasOne("BotGlobal.PlatformClients.Domain.PlatformClient", null)
                        .WithMany("Credentials")
                        .HasForeignKey("ClientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("BotGlobal.PlatformClients.Domain.PlatformClient", b =>
                {
                    b.Navigation("Capabilities");

                    b.Navigation("Credentials");
                });
#pragma warning restore 612, 618
        }
    }
}
