<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\SentriCam.Domain\SentriCam.Domain.csproj" />
    <ProjectReference Include="..\SentriCam.Contracts\SentriCam.Contracts.csproj" />
    <ProjectReference Include="..\SentriCam.Shared\SentriCam.Shared.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="FluentValidation.DependencyInjectionExtensions" />
    <PackageReference Include="Microsoft.Extensions.Logging.Abstractions" />
  </ItemGroup>

</Project>
